// Chichu Art Museum — regenerated under the isolated Meowseum pipeline.
museumData.chichu = {
  ...museumRatings.chichu,
  ...{
  "id": "chichu",
  "editorialCapacity": 20,
  "city": "直岛 · 日本",
  "zh": "地中美术馆",
  "en": "Chichu Art Museum",
  "verdict": "如果已经安排直岛行程，地中美术馆应列为优先目的地，并预留至少半天；若只按稀世名作密度决定旅行，它不足以单独支撑一次前往直岛的行程。",
  "hero": "https://benesse-artsite.jp/en/art/chichu_kv_thumb_01_sp.jpg",
  "contentFile": "./research/content/chichu.md",
  "official": "https://benesse-artsite.jp/en/art/chichu.html",
  "visit": "https://benesse-artsite.jp/en/general-information.html",
  "cardCopyContract": "independent-v1",
  "intro": [
    "安藤忠雄用埋入山体的混凝土、露天几何庭院和专用展厅限制光进入的方式；莫奈的水面、塔瑞尔的光室与德·玛利亚的固定几何体因此都不再拥有一个恒定外观。这里最值得看的不是建筑、作品或自然中的单独一项，而是三者怎样共同把观看变成一段随身体移动和时刻变化的过程。",
    "安藤忠雄把建筑大半埋入山体，并为莫奈、詹姆斯·塔瑞尔和沃尔特·德·玛利亚分别设计永久空间；路线、自然光、作品与天气共同构成高度不可复制的现场。20项中有11项达到重要藏品，但没有一项通过“稀世珍品”的全球不可替代性硬门，因此最高只能停在70档。",
    "馆藏集中于三位艺术家，20项中多项是同一建筑的观看节点，不能按20件独立名作理解。预约、开放日、维护与塔瑞尔夜间项目会变化；馆内摄影规则和当天作品状态须以馆方为准。"
  ],
  "chapters": [
    {
      "id": "buried-museum",
      "number": "01",
      "title": "建筑消失以后，靠什么带你进入地下？",
      "intro": "从地表轮廓到入口、坡道和两座庭院，解释“地中”不是外形噱头，而是一套用遮挡、转折、几何与露天开口建立方向的路线。"
    },
    {
      "id": "measured-daylight",
      "number": "02",
      "title": "自然光既然会变，展厅怎样把变化变成秩序？",
      "intro": "说明自然光并非未经设计地落入地下；开口、吊顶、材料和测光共同让时间可见，并为莫奈作品建立专用环境。"
    },
    {
      "id": "monet-water",
      "number": "03",
      "title": "没有岸和地平线，莫奈怎样只用水面撑起五幅画？",
      "intro": "以建馆契机的六米双联画为核心，对照方形、横幅、草丛和柳影，讲清莫奈晚期如何用浮叶、反射与松散笔触替代传统远景。"
    },
    {
      "id": "turrell-perception",
      "number": "04",
      "title": "光什么时候像物体，什么时候又像一间房？",
      "intro": "按1968、2000、2004年的顺序比较塔瑞尔从墙角投影、空间开口到真实天空的三种方法，让观众用移动和颜色对比检查自己的知觉。"
    },
    {
      "id": "changing-time",
      "number": "05",
      "title": "不动的石球与生长的庭园，怎样各自记录时间？",
      "intro": "以德·玛利亚的固定几何和地中庭园的季节变化收束全馆：时间既能通过光在材料上的移动显现，也能通过植物的生长与花期显现。"
    }
  ],
  "works": [
    {
      "id": "whole",
      "ch": "buried-museum",
      "zh": "地中美术馆整体",
      "en": "Chichu Art Museum as a Whole",
      "by": "安藤忠雄 Tadao Ando 设计；与克劳德·莫奈 Claude Monet、詹姆斯·特瑞尔 James Turrell、沃尔特·德·玛利亚 Walter De Maria 的永久陈列共同形成",
      "date": "2004 年开放",
      "place": "日本香川县直岛町 3449-1；三位艺术家的作品为永久陈列，实际开放与可见性以馆方当日信息为准",
      "tag": "绝对不可错过",
      "significance": "重要藏品",
      "time": "贯穿全馆参观，全程留意建筑、天光与路线的变化",
      "image": "./assets/chichu/architecture-context.jpg",
      "imageKind": "context-image",
      "imagePolicy": "context_image",
      "imageResolutionStatus": "context_image_accepted",
      "imageEvidenceSha256": "a8385b47d436658d4724c2640dae7dcfcbb540f5348c41f6244227fc9cd44d38",
      "imageSource": "https://benesse-artsite.jp/en/art/chichu.html",
      "imageCaption": "馆方地中美术馆主图：用于辨认建筑与地形关系。",
      "source": "https://benesse-artsite.jp/en/art/chichu.html",
      "cardSummary": "这座馆值得看的不只是三位艺术家的永久陈列，更是建筑怎样把山丘、天光和行走路线纳入作品：地表只露出几何切口，进入地下后，每一次转弯、见天和抵达专用展厅，都在改变你与艺术相遇的条件。",
      "preciousWhy": "这座馆值得看的不只是三位艺术家的永久陈列，更是建筑怎样把山丘、天光和行走路线纳入作品：地表只露出几何切口，进入地下后，每一次转弯、见天和抵达专用展厅，都在改变你与艺术相遇的条件。"
    },
    {
      "id": "hidden-profile",
      "ch": "buried-museum",
      "zh": "近乎隐形的地表轮廓",
      "en": "The Nearly Invisible Profile",
      "by": "安藤忠雄 Tadao Ando · 日本",
      "date": "2004",
      "place": "直岛山丘；建筑外部与俯视关系持续可见，具体可接近范围依现场管理",
      "tag": "强烈推荐",
      "significance": "体验补充",
      "time": "约 3—5 分钟",
      "image": "https://benesse-artsite.jp/en/art/chichu_architecture_thumb_01.jpg",
      "imageSource": "https://benesse-artsite.jp/en/art/chichu.html",
      "imageCaption": "馆方安藤建筑配图：用于辨认地下几何空间；不是当前节点的独立对象照。",
      "source": "https://benesse-artsite.jp/en/art/chichu.html",
      "cardSummary": "山丘仍像山丘，美术馆却已经在脚下展开。安藤忠雄把大部分建筑压入地下，只让三角形、方形切口和深色阴影露出地面：它值得停下来，因为这几道克制的轮廓，正是整座美术馆如何兼顾景观、方向与自然光的第一份说明。",
      "preciousWhy": "山丘仍像山丘，美术馆却已经在脚下展开。安藤忠雄把大部分建筑压入地下，只让三角形、方形切口和深色阴影露出地面：它值得停下来，因为这几道克制的轮廓，正是整座美术馆如何兼顾景观、方向与自然光的第一份说明。"
    },
    {
      "id": "entrance-cut",
      "ch": "buried-museum",
      "zh": "入口切口",
      "en": "The Entrance Cut",
      "by": "安藤忠雄 Tadao Ando · 日本",
      "date": "2004",
      "place": "地中美术馆主馆入口 · 随建筑持续使用",
      "tag": "强烈推荐",
      "significance": "体验补充",
      "time": "约 3 分钟",
      "image": "https://benesse-artsite.jp/en/art/chichu_kv_thumb_01_sp.jpg",
      "imageSource": "https://benesse-artsite.jp/en/art/chichu.html",
      "imageCaption": "馆方地中美术馆主图：用于辨认建筑与地形关系。",
      "source": "https://benesse-artsite.jp/en/contact/press/BASN_MediaKit_Jan2016_GenegalPress_eng.pdf",
      "cardSummary": "这道混凝土窄口没有把美术馆的全貌摆在眼前：下行、转折和遮挡迫使建筑随着脚步逐段出现。它值得停留，因为地中美术馆的参观并非进门后才开始，跨过这道墙时，空间已经在改变你的观看方式。",
      "preciousWhy": "这道混凝土窄口没有把美术馆的全貌摆在眼前：下行、转折和遮挡迫使建筑随着脚步逐段出现。它值得停留，因为地中美术馆的参观并非进门后才开始，跨过这道墙时，空间已经在改变你的观看方式。"
    },
    {
      "id": "concrete-ramp",
      "ch": "buried-museum",
      "zh": "混凝土坡道与转折",
      "en": "Concrete Ramps and Turns",
      "by": "安藤忠雄 Tadao Ando · 国别未在研究卡注明",
      "date": "2004",
      "place": "地中美术馆入口至庭院及展厅之间的主馆动线；持续使用",
      "tag": "强烈推荐",
      "significance": "体验补充",
      "time": "随主馆动线行走时留意，无需另行绕路",
      "image": "https://benesse-artsite.jp/en/art/chichu_architecture_thumb_01.jpg",
      "imageSource": "https://benesse-artsite.jp/en/art/chichu.html",
      "imageCaption": "馆方安藤建筑配图：用于辨认地下几何空间；不是当前节点的独立对象照。",
      "source": "https://benesse-artsite.jp/en/art/chichu.html",
      "cardSummary": "安藤忠雄把通往展厅的移动也做成了观看：混凝土墙遮住前方，高差不断改变视线，天光在暗处划出方向。走过这些坡道和转角，才会明白地中美术馆的空间不是一眼看完的，而是一步步出现的。",
      "preciousWhy": "安藤忠雄把通往展厅的移动也做成了观看：混凝土墙遮住前方，高差不断改变视线，天光在暗处划出方向。走过这些坡道和转角，才会明白地中美术馆的空间不是一眼看完的，而是一步步出现的。"
    },
    {
      "id": "square-court",
      "ch": "buried-museum",
      "zh": "方形庭院",
      "en": "Square Courtyard",
      "by": "安藤忠雄 Tadao Ando · 日本",
      "date": "2004",
      "place": "入口区域；随建筑持续可见，庭院本体通常从周边路径观看",
      "tag": "强烈推荐",
      "significance": "特色看点",
      "time": "3—5 分钟",
      "image": "https://benesse-artsite.jp/en/art/chichu_architecture_thumb_01.jpg",
      "imageSource": "https://benesse-artsite.jp/en/art/chichu.html",
      "imageCaption": "馆方安藤建筑配图：用于辨认地下几何空间；不是当前节点的独立对象照。",
      "source": "https://benesse-artsite.jp/en/contact/press/BASN_MediaKit_Jan2016_GenegalPress_eng.pdf",
      "cardSummary": "四面混凝土高墙没有把地下入口彻底封住，而是围出一块有天空、天光和木贼类植物的方形空洞。它把地中美术馆的几何秩序变成一次身体经验：穿过较暗的通道，方向和亮度会在这里一起改变。",
      "preciousWhy": "四面混凝土高墙没有把地下入口彻底封住，而是围出一块有天空、天光和木贼类植物的方形空洞。它把地中美术馆的几何秩序变成一次身体经验：穿过较暗的通道，方向和亮度会在这里一起改变。"
    },
    {
      "id": "trench-passage",
      "ch": "buried-museum",
      "zh": "槽状露天通道",
      "en": "Gutter-Shaped Outdoor Passage",
      "by": "安藤忠雄 Tadao Ando · 日本",
      "date": "2004",
      "place": "主馆地下动线，随建筑持续使用",
      "tag": "强烈推荐",
      "significance": "体验补充",
      "time": "随主馆动线通过，放慢脚步观察",
      "image": "https://benesse-artsite.jp/en/art/chichu_architecture_thumb_01.jpg",
      "imageSource": "https://benesse-artsite.jp/en/art/chichu.html",
      "imageCaption": "馆方安藤建筑配图：用于辨认地下几何空间；不是当前节点的独立对象照。",
      "source": "https://benesse-artsite.jp/en/contact/press/BASN_MediaKit_Jan2016_GenegalPress_eng.pdf",
      "cardSummary": "这条露天通道把地中美术馆的“走过去”也变成作品：高墙收住横向视野，墙顶之间却保留天空，访客由方形庭院走向三角形庭院时，光线、空气与天气也一同进入地下路线。",
      "preciousWhy": "这条露天通道把地中美术馆的“走过去”也变成作品：高墙收住横向视野，墙顶之间却保留天空，访客由方形庭院走向三角形庭院时，光线、空气与天气也一同进入地下路线。"
    },
    {
      "id": "triangle-court",
      "ch": "buried-museum",
      "zh": "三角庭院",
      "en": "Triangular Courtyard",
      "by": "安藤忠雄 Tadao Ando",
      "date": "2004",
      "place": "地中美术馆主馆画廊枢纽；随建筑持续可见",
      "tag": "绝对不可错过",
      "significance": "特色看点",
      "time": "5—10 分钟",
      "image": "https://benesse-artsite.jp/en/art/chichu_architecture_thumb_01.jpg",
      "imageSource": "https://benesse-artsite.jp/en/art/chichu.html",
      "imageCaption": "馆方安藤建筑配图：用于辨认地下几何空间；不是当前节点的独立对象照。",
      "source": "https://benesse-artsite.jp/en/contact/press/BASN_MediaKit_Jan2016_GenegalPress_eng.pdf",
      "cardSummary": "这座露天三角形不是展厅之间的空白，而是安藤忠雄用来组织整段地下参观的空间枢纽：三条边把三位艺术家的展厅变成不同去向，高墙框住不断变化的天空，浅色乱石又让精确的混凝土几何多出脚下的触感。它值得停下，因为路线、天气和材料在这里同时成为观看内容。",
      "preciousWhy": "这座露天三角形不是展厅之间的空白，而是安藤忠雄用来组织整段地下参观的空间枢纽：三条边把三位艺术家的展厅变成不同去向，高墙框住不断变化的天空，浅色乱石又让精确的混凝土几何多出脚下的触感。它值得停下，因为路线、天气和材料在这里同时成为观看内容。"
    },
    {
      "id": "daylight-clock",
      "ch": "measured-daylight",
      "zh": "作为无形时钟的日光",
      "en": "Daylight as an Invisible Clock",
      "by": "安藤忠雄与受委托艺术家的空间协作",
      "date": "2004 至今",
      "place": "全馆；永久建筑机制，光况随时刻、天气与季节变化",
      "tag": "绝对不可错过",
      "significance": "特色看点",
      "time": "贯穿全程，随路线持续观察",
      "image": "https://benesse-artsite.jp/en/story/uploads/story/blog20201029_04.jpg",
      "imageSource": "https://benesse-artsite.jp/en/art/chichu.html",
      "imageCaption": "馆方采光实验模型照片：用于解释自然光设计，不是现场展品。",
      "source": "https://benesse-artsite.jp/en/art/chichu.html",
      "cardSummary": "地中美术馆把日光变成一条贯穿参观的时间线：庭院的阴影、莫奈空间的间接天光，以及德·玛利亚空间里石球与贴金木雕的外观，都不会整日固定。它值得一路留意，因为建筑并未消除天气与季节的变化，而是让这些变化落到作品和材料表面。",
      "preciousWhy": "地中美术馆把日光变成一条贯穿参观的时间线：庭院的阴影、莫奈空间的间接天光，以及德·玛利亚空间里石球与贴金木雕的外观，都不会整日固定。它值得一路留意，因为建筑并未消除天气与季节的变化，而是让这些变化落到作品和材料表面。"
    },
    {
      "id": "monet-room",
      "ch": "measured-daylight",
      "zh": "克劳德·莫奈空间",
      "en": "Claude Monet Space",
      "by": "秋元雄史 Yūji Akimoto、安藤忠雄 Tadao Ando · 日本；展示克劳德·莫奈 Claude Monet · 法国",
      "date": "2004年开放；展示莫奈晚期作品",
      "place": "地中美术馆永久陈列空间；实际可见性以现场维护为准",
      "tag": "绝对不可错过",
      "significance": "重要藏品",
      "time": "10—15分钟",
      "image": "https://benesse-artsite.jp/en/story/uploads/story/blog20201029_01.jpg",
      "imageSource": "https://benesse-artsite.jp/en/story/20210611-1671.html",
      "imageCaption": "馆方莫奈空间照片：可见自然光、白色曲面与作品陈列关系。",
      "source": "https://benesse-artsite.jp/en/art/chichu.html",
      "cardSummary": "五幅晚期《睡莲》之所以值得专程走进这个白色房间，是因为画、天光、圆弧墙角和嵌墙展柜被当作一个整体设计。这里最特别的并非单独多挂了几幅莫奈，而是让连续水面尽量少受墙角、硬边框与强烈灯斑打断，接近他为“大装饰画”设想的包围式观看。",
      "preciousWhy": "五幅晚期《睡莲》之所以值得专程走进这个白色房间，是因为画、天光、圆弧墙角和嵌墙展柜被当作一个整体设计。这里最特别的并非单独多挂了几幅莫奈，而是让连续水面尽量少受墙角、硬边框与强烈灯斑打断，接近他为“大装饰画”设想的包围式观看。"
    },
    {
      "id": "marble-floor",
      "ch": "measured-daylight",
      "zh": "手工铺设的大理石地面",
      "en": "The Hand-Laid Marble Floor",
      "by": "安藤忠雄团队与施工工匠",
      "date": "2004年启用",
      "place": "地中美术馆莫奈室固定建筑构件；开放与通行状态以馆方为准",
      "tag": "时间充裕再看",
      "significance": "体验补充",
      "time": "2—3分钟",
      "image": "https://benesse-artsite.jp/en/story/uploads/story/blog20201029_05.jpg",
      "imageSource": "https://benesse-artsite.jp/en/story/20210611-1671.html",
      "imageCaption": "馆方施工档案：莫奈空间手工铺设的大理石地面。",
      "source": "https://benesse-artsite.jp/en/story/20210611-1671.html",
      "cardSummary": "莫奈室最费工的部分之一，恰恰安静得像背景：约70万块两厘米见方的卡拉拉白色大理石由人工逐块铺成。接缝、细微色差和脚步的尺度，让自然光下的白色展室不是一张空白底板，而是一处由建筑、身体与工匠劳动共同完成的观看环境。",
      "preciousWhy": "莫奈室最费工的部分之一，恰恰安静得像背景：约70万块两厘米见方的卡拉拉白色大理石由人工逐块铺成。接缝、细微色差和脚步的尺度，让自然光下的白色展室不是一张空白底板，而是一处由建筑、身体与工匠劳动共同完成的观看环境。"
    },
    {
      "id": "water-lily-pond-1915",
      "ch": "monet-water",
      "zh": "睡莲池，约 1915—1926",
      "en": "Water-Lily Pond, circa 1915–1926",
      "by": "克劳德·莫奈 Claude Monet · 法国",
      "date": "约 1915—1926",
      "place": "地中美术馆 Claude Monet Space；永久陈列组之一，在展与维护状态以馆方当日信息为准",
      "tag": "绝对不可错过",
      "significance": "重要藏品",
      "time": "8—12 分钟",
      "image": "./assets/chichu/water-lily-pond-c-1915-1926.jpg",
      "imageResolutionStatus": "object_image_accepted",
      "imageEvidenceSha256": "c6113fab801c7cf5abf2453fb15bb8016029e3308229c12b7e362cb34958e306",
      "imageSource": "https://commons.wikimedia.org/wiki/File:Monet_Waterlilypond_1926.jpg",
      "imageCaption": "《睡莲的池塘》完整作品图；作品身份以地中美术馆官方清单核对。",
      "source": "https://benesse-artsite.jp/en/art/chichu.html",
      "cardSummary": "六米长的水面把莫奈晚年的变化说得很清楚：池塘不再是隔着画框观看的一处风景，而开始占据观众的整个视野。更特别的是，这幅画后来直接促成了地中美术馆和专用展厅的诞生，作品与空间在这里成了同一个观看经验。",
      "preciousWhy": "六米长的水面把莫奈晚年的变化说得很清楚：池塘不再是隔着画框观看的一处风景，而开始占据观众的整个视野。更特别的是，这幅画后来直接促成了地中美术馆和专用展厅的诞生，作品与空间在这里成了同一个观看经验。"
    },
    {
      "id": "cluster-grass",
      "ch": "monet-water",
      "zh": "睡莲—草丛",
      "en": "Water Lilies, Cluster of Grass",
      "by": "克洛德·莫奈 Claude Monet · 法国",
      "date": "1914—1917",
      "place": "地中美术馆莫奈室 · 馆方列为永久陈列，当日可见性以馆方为准",
      "tag": "强烈推荐",
      "significance": "重要藏品",
      "time": "多停几分钟",
      "image": "./assets/chichu/water-lilies-cluster-of-grass-1914-1917.jpg",
      "imageResolutionStatus": "object_image_accepted",
      "imageEvidenceSha256": "a6a55de64ad1aee9488ee9c0a7412251c07916a5c1b001bd5b2c1c0e50d13011",
      "imageSource": "https://commons.wikimedia.org/wiki/File:Monet-Water-lilies-cluster-of-grass-Chichu-museum.tif",
      "imageCaption": "馆方莫奈章节配图：对应馆内五幅《睡莲》收藏组；不是每幅作品的独立正面图。",
      "source": "https://benesse-artsite.jp/en/art/chichu.html",
      "cardSummary": "这张近方形《睡莲》把莫奈晚年的一次关键变化压缩得格外清楚：池岸和地平线退出画面，睡莲叶、直立草形与倒影各自提供一部分空间线索。眼睛既看见池塘，又会不断碰到油彩本身；它值得点开，正因为一幅风景在这里开始摆脱稳定的远近秩序。",
      "preciousWhy": "这张近方形《睡莲》把莫奈晚年的一次关键变化压缩得格外清楚：池岸和地平线退出画面，睡莲叶、直立草形与倒影各自提供一部分空间线索。眼睛既看见池塘，又会不断碰到油彩本身；它值得点开，正因为一幅风景在这里开始摆脱稳定的远近秩序。"
    },
    {
      "id": "water-lilies-1914",
      "ch": "monet-water",
      "zh": "睡莲",
      "en": "Water Lilies",
      "by": "克洛德·莫奈 Claude Monet · 法国",
      "date": "1914—1917",
      "place": "地中美术馆莫奈室 · 永久陈列组成员，具体当日可见性以馆方为准",
      "tag": "强烈推荐",
      "significance": "重要藏品",
      "time": "5—8 分钟",
      "image": "./assets/chichu/water-lilies-1914-1917.jpg",
      "imagePolicy": "object_image",
      "imageResolutionStatus": "object_image_accepted",
      "imageEvidenceSha256": "ef0e3ac441f882365b47736ca1039d16071af5242eabe52a2c4da21e3f8f181b",
      "imageSource": "https://commons.wikimedia.org/wiki/File:Monet-Water-lilies-Chichu-museum.tif",
      "imageCaption": "《睡莲》，1914—1917；图片来自 Wikimedia Commons 的作品文件页。",
      "source": "https://benesse-artsite.jp/en/art/chichu.html",
      "cardSummary": "莫奈在这幅方形《睡莲》里撤掉岸线、远景和唯一主角，让池水、浮叶与倒影铺到画布四边。它值得点开，不只因为色彩迷人，更因为你能在一幅仍画着真实水园的作品里，看见传统风景怎样开始变成无中心、近乎包围观众的视觉环境。",
      "preciousWhy": "莫奈在这幅方形《睡莲》里撤掉岸线、远景和唯一主角，让池水、浮叶与倒影铺到画布四边。它值得点开，不只因为色彩迷人，更因为你能在一幅仍画着真实水园的作品里，看见传统风景怎样开始变成无中心、近乎包围观众的视觉环境。"
    },
    {
      "id": "water-lily-pond-1917",
      "ch": "monet-water",
      "zh": "睡莲池",
      "en": "Water-Lily Pond",
      "by": "克洛德·莫奈 Claude Monet · 法国",
      "date": "1917—1919",
      "place": "地中美术馆莫奈室；永久陈列组成员，当日可见性以馆方为准",
      "tag": "强烈推荐",
      "significance": "重要藏品",
      "time": "6—8 分钟",
      "image": "./assets/chichu/water-lily-pond-1917-1919.jpg",
      "imageResolutionStatus": "object_image_accepted",
      "imageEvidenceSha256": "1ef30027460dba6a1da98673804245a806c245a7276fcfdacf1a56ee08905ea7",
      "imageSource": "https://commons.wikimedia.org/wiki/File:The_Water_Lily_Pond_(1917-1919)_Claude_Monet_-_Chichu_Art_Museum_(W1896).jpg",
      "imageCaption": "馆方莫奈章节配图：对应馆内五幅《睡莲》收藏组；不是每幅作品的独立正面图。",
      "source": "https://benesse-artsite.jp/en/art/chichu.html",
      "cardSummary": "这不是一幅把池塘交代完整的风景，而是莫奈晚年从水面截下的一段：岸、桥和地平线全部退出，睡莲与倒影仿佛还能越过画框继续铺开。横向叶群和竖向色痕让眼睛在平面与深处之间来回切换，也把这幅独立画布接入他“大装饰画”时期更辽阔的构想。",
      "preciousWhy": "这不是一幅把池塘交代完整的风景，而是莫奈晚年从水面截下的一段：岸、桥和地平线全部退出，睡莲与倒影仿佛还能越过画框继续铺开。横向叶群和竖向色痕让眼睛在平面与深处之间来回切换，也把这幅独立画布接入他“大装饰画”时期更辽阔的构想。"
    },
    {
      "id": "willow-reflections",
      "ch": "monet-water",
      "zh": "睡莲—垂柳倒影",
      "en": "Water Lilies, Reflections of Weeping Willows",
      "by": "克洛德·莫奈 Claude Monet · 法国",
      "date": "1916—1919",
      "place": "地中美术馆莫奈室；永久陈列组成员，当日可见性以馆方为准",
      "tag": "强烈推荐",
      "significance": "重要藏品",
      "time": "5—8 分钟",
      "image": "./assets/chichu/water-lilies-reflections-of-weeping-willows-1916-1919.jpg",
      "imageResolutionStatus": "object_image_accepted",
      "imageEvidenceSha256": "4741918b5eed4310acc4a685f390f42d8ff7380244212b7b6be87e6ca9eefc80",
      "imageSource": "https://commons.wikimedia.org/wiki/File:Nympheas,_reflets_de_saule_-_Water-Lilies,_Reflections_of_Weeping_Willows_(1916-19)_Claude_Monet_-_Chichu_Museum_of_Art_(W_1857).jpg",
      "imageCaption": "馆方莫奈章节配图：对应馆内五幅《睡莲》收藏组；不是每幅作品的独立正面图。",
      "source": "https://benesse-artsite.jp/en/art/chichu.html",
      "cardSummary": "莫奈把浮在水面的睡莲与向下垂落的柳树倒影压进同一片颜料，让水面既像有深度的池塘，又不断显露为一张画布。岸线消失后，扁平叶片和纵向柳影反而成了辨认空间的线索，也让这幅晚期代表作值得多看几分钟。",
      "preciousWhy": "莫奈把浮在水面的睡莲与向下垂落的柳树倒影压进同一片颜料，让水面既像有深度的池塘，又不断显露为一张画布。岸线消失后，扁平叶片和纵向柳影反而成了辨认空间的线索，也让这幅晚期代表作值得多看几分钟。"
    },
    {
      "id": "afrum",
      "ch": "turrell-perception",
      "zh": "阿弗鲁姆，淡蓝",
      "en": "Afrum, Pale Blue",
      "by": "詹姆斯·塔瑞尔 James Turrell · 美国",
      "date": "1968年",
      "place": "地中美术馆塔瑞尔空间 · 永久陈列，当日可见性以馆方为准",
      "tag": "绝对不可错过",
      "significance": "重要藏品",
      "time": "5—8分钟",
      "image": "./assets/chichu/james-turrell-afrum-pale-blue-1968.jpg",
      "imageKind": "installation",
      "imagePolicy": "object_image",
      "imageResolutionStatus": "object_image_accepted",
      "imageEvidenceSha256": "b8c37451e8253d5a3940207784d540088f70090f351a3a47ae1333d928642669",
      "imageSource": "https://unpointculture.wordpress.com/2016/02/16/larchitecture-comme-paysage-et-lieu-de-loeuvre-tadao-ando-au-chichu-art-museum-de-naoshima/images-1-2/",
      "imageCaption": "《Afrum，浅蓝》现场图；来源页标题明确标注作品、年份与地中美术馆。",
      "source": "https://benesse-artsite.jp/en/art/chichu.html",
      "cardSummary": "塔瑞尔没有做出一只发光的盒子，却让两面墙上的淡蓝投影显得有体积。它值得点开，因为只需靠近几步，一个看似坚实的形体便会显出光与墙角的关系，让人亲眼经历“看见”是怎样被空间组织出来的。",
      "preciousWhy": "塔瑞尔没有做出一只发光的盒子，却让两面墙上的淡蓝投影显得有体积。它值得点开，因为只需靠近几步，一个看似坚实的形体便会显出光与墙角的关系，让人亲眼经历“看见”是怎样被空间组织出来的。"
    },
    {
      "id": "open-field",
      "ch": "turrell-perception",
      "zh": "开放的场域",
      "en": "Open Field",
      "by": "詹姆斯·塔瑞尔 James Turrell · 美国",
      "date": "2000",
      "place": "地中美术馆塔瑞尔空间，永久陈列；进入方式与当日状态以馆方现场指引为准",
      "tag": "绝对不可错过",
      "significance": "重要藏品",
      "time": "8—12 分钟，并按现场指引从不同距离观看",
      "image": "./assets/chichu/james-turrell-open-field-2000.png",
      "imageKind": "installation",
      "imagePolicy": "object_image",
      "imageResolutionStatus": "object_image_accepted",
      "imageEvidenceSha256": "b5c3003bc9020c63d282087569ae17dd0080e8b75e248cad47582062cac9ce4b",
      "imageSource": "https://artsandculture.google.com/asset/open-field-2000-james-turrel-chichu-art-museum-tadao-ando/1QEVcCgYYo-G8g?hl=en",
      "imageCaption": "《开放场域》展陈现场图；已从来源页的主图容器中提取，未包含网页导航与页脚。",
      "source": "https://benesse-artsite.jp/en/art/chichu.html",
      "cardSummary": "一片蓝光为什么值得专门走近？因为塔瑞尔没有把它画在墙上，而是让一处真实的房间开口暂时失去深度：距离改变，平面就重新显出空间，观众也亲自经历了眼睛怎样修正判断。",
      "preciousWhy": "一片蓝光为什么值得专门走近？因为塔瑞尔没有把它画在墙上，而是让一处真实的房间开口暂时失去深度：距离改变，平面就重新显出空间，观众也亲自经历了眼睛怎样修正判断。"
    },
    {
      "id": "open-sky",
      "ch": "turrell-perception",
      "zh": "开放的天空",
      "en": "Open Sky",
      "by": "詹姆斯·塔瑞尔 James Turrell · 美国",
      "date": "2004",
      "place": "地中美术馆永久设置；日落夜间项目需另行预约，实时安排以馆方为准",
      "tag": "绝对不可错过",
      "significance": "重要藏品",
      "time": "常规观看 10—15 分钟；夜间项目约 45 分钟",
      "image": "./assets/chichu/james-turrell-open-sky-2004.png",
      "imageKind": "context-image",
      "imagePolicy": "context_image",
      "imageResolutionStatus": "context_image_accepted",
      "imageEvidenceSha256": "77c81c506344a394369b42905016534db6c02fb21366d63a0731ebe7d85a0c74",
      "imageSource": "https://artsandculture.google.com/asset/chichu-art-museum-naoshima-architect-tadao-ando-james-turrell-and-photographer-john-barr/7QHAAu509lZDSw",
      "imageCaption": "《开放天空》建筑／场域图；已从来源页的主图容器中提取，未包含网页导航与页脚。",
      "source": "https://benesse-artsite.jp/en/art/chichu.html",
      "cardSummary": "塔瑞尔把真正的天空纳入一座专门空间：规整开口、变化的室内彩光与直岛的天气彼此作用，让天空有时像一块贴近天花板的色面。它值得停下来看的，正是建筑没有替你画出天空，却改变了眼睛怎样看见天空。",
      "preciousWhy": "塔瑞尔把真正的天空纳入一座专门空间：规整开口、变化的室内彩光与直岛的天气彼此作用，让天空有时像一块贴近天花板的色面。它值得停下来看的，正是建筑没有替你画出天空，却改变了眼睛怎样看见天空。"
    },
    {
      "id": "time-timeless",
      "ch": "changing-time",
      "zh": "时间／无时间／没有时间",
      "en": "Time/Timeless/No Time",
      "by": "沃尔特·德·玛利亚 Walter De Maria · 美国",
      "date": "2004",
      "place": "地中美术馆永久设置；当日开放以馆方为准",
      "tag": "绝对不可错过",
      "significance": "重要藏品",
      "time": "8—12 分钟",
      "image": "./assets/chichu/walter-de-maria-time-timeless-no-time-2004.png",
      "imageKind": "installation",
      "imagePolicy": "object_image",
      "imageResolutionStatus": "object_image_accepted",
      "imageEvidenceSha256": "4ff1676a6bf2dc81a47f132b6d3c83b01877493eede138ccd2238bbf0e92773a",
      "imageSource": "https://artsandculture.google.com/asset/%E2%80%9Ctime-timeless-no-time%E2%80%9D-2004-walter-de-maria-chichu-art-museum-tadao-ando/EwEmdBYaTmcp3g?hl=en",
      "imageCaption": "《时间／无时／无时间》展陈现场图；已从来源页的主图容器中提取，未包含网页导航与页脚。",
      "source": "https://benesse-artsite.jp/en/art/chichu.html",
      "cardSummary": "德·玛利亚把巨大的石球、金色几何体与整座房间做成一套固定系统，再让日光和人的移动不断改写它。值得停下来的，是看一件纹丝不动的作品怎样把时间变成反光、明暗与遮挡。",
      "preciousWhy": "德·玛利亚把巨大的石球、金色几何体与整座房间做成一套固定系统，再让日光和人的移动不断改写它。值得停下来的，是看一件纹丝不动的作品怎样把时间变成反光、明暗与遮挡。"
    },
    {
      "id": "chichu-garden",
      "ch": "changing-time",
      "zh": "地中庭园",
      "en": "Chichu Garden",
      "by": "地中美术馆庭园团队 · 日本",
      "date": "随地中美术馆项目建成并持续养护",
      "place": "地中美术馆入口一带；植物与景观随季节、天气及养护变化",
      "tag": "时间充裕再看",
      "significance": "体验补充",
      "time": "5—10 分钟",
      "image": "https://benesse-artsite.jp/en/art/uploads/art/garden.jpg",
      "imageSource": "https://benesse-artsite.jp/en/art/chichu.html",
      "imageCaption": "馆方地中庭园照片：对应进馆前的植物序列。",
      "source": "https://benesse-artsite.jp/en/art/chichu.html",
      "cardSummary": "这座入口庭园值得留几分钟，因为它把莫奈画中的睡莲、柳树与鸢尾重新变成会生长、会随季节改变的环境。沿园路换几个角度，你会明白《睡莲》背后不只有一片池水，还有一位画家先营造花园、再长期观察它的过程。",
      "preciousWhy": "这座入口庭园值得留几分钟，因为它把莫奈画中的睡莲、柳树与鸢尾重新变成会生长、会随季节改变的环境。沿园路换几个角度，你会明白《睡莲》背后不只有一片池水，还有一位画家先营造花园、再长期观察它的过程。"
    }
  ]
}
};
