const louvreChapters = [
  {id:"fame",number:"01",title:"名作是怎样被制造出来的",intro:"作品、复原、收藏、陈列与人群共同生产名气；先看它，再看卢浮宫怎样让它成为名作。"},
  {id:"history",number:"02",title:"权力、战争与灾难怎样变成图像",intro:"从苏美尔军阵到法国革命，图像并不只是记录历史，它也在替国家安排谁被记住。"},
  {id:"belief",number:"03",title:"人怎样接近神、死亡与来世",intro:"墓室、棺木、守护神和宗教绘画把死亡之后的秩序变成材料、空间与身体。"},
  {id:"body",number:"04",title:"材料怎样让身体获得重量",intro:"理想、欲望、挣扎和死亡都要靠石头的重心、表面与观看角度具体发生。"},
  {id:"gaze",number:"05",title:"画家怎样控制目光、心理和时间",intro:"画面不只提供故事；光线、笔触、姿态和空间会决定你先看谁、停多久、相信什么。"},
  {id:"palace",number:"06",title:"宫殿、收藏与国家怎样改写物件",intro:"对象离开神庙、宫廷或住宅进入卢浮宫以后，会失去旧语境，也会获得新的国家身份。"},
  {id:"hidden",number:"07",title:"冷门但值得",intro:"它们常被明星作品遮住，却各自提供不可替代的技术、历史或观看回报；冷门不等于不重要。"}
];

const louvreImages = {
  victory:"The Winged Victory of Samothrace.jpg", venus:"Venus de Milo Louvre Ma399.jpg", mona:"Mona Lisa, by Leonardo da Vinci, from C2RMF retouched.jpg", cana:"Musée du Louvre - Les noces de Cana.jpg",
  coronation:"Jacques-Louis David, The Coronation of Napoleon.jpg", raft:"The Raft of the Medusa - Louvre.jpg", liberty:"La Liberté guidant le peuple - Eugène Delacroix - Musée du Louvre Peintures RF 129 - après restauration 2024.jpg",
  hammurabi:"Code Of Hammurabi.jpg", lamassu:"Human headed winged bull Louvre AO19859.jpg", sphinx:"Great Sphinx of Tanis, Paris alt.jpg", scribe:"Le Scribe accroupi - Musée du Louvre Antiquités égyptiennes E 3023.jpg",
  psyche:"0 Psyché ranimée par le baiser de l'Amour - Canova - Louvre 1.JPG", hermaphroditus:"Louvre - Sleeping Hermaphroditus 01.jpg", diana:"Diane de Versailles - Musée du Louvre AGER Ma 589.jpg",
  slaves:"Dying and Rebellious Slaves by Michelangelo (Louvre).jpg", anne:"Leonardo da Vinci - Virgin and Child with St Anne C2RMF retouched.jpg", odalisque:"La grande odalisque - Jean-Auguste Dominique Ingres - Musée du Louvre Peintures RF 1158.jpg",
  botticelli:"Vénus et les trois Grâces offrant des présents à une jeune fille - Sandro Botticelli - Musée du Louvre Peintures RF 321.jpg", basin:"Bassin Syrie 3.JPG", regent:"Le Régent - Joseph Cope - Musée du Louvre Objets d'art MV 1017.jpg"
};

const louvreSources = {
  victory:"https://collections.louvre.fr/en/ark:/53355/cl010252531", venus:"https://www.louvre.fr/en/explore/visitor-trails/the-louvre-s-masterpieces/a-welcome-newcomer-to-the-louvre",
  mona:"https://www.louvre.fr/en/explore/visitor-trails/the-louvre-s-masterpieces/a-superstar-and-a-wedding-crowd", cana:"https://www.louvre.fr/en/explore/visitor-trails/the-louvre-s-masterpieces/a-superstar-and-a-wedding-crowd",
  coronation:"https://www.louvre.fr/en/explore/the-palace/think-big", raft:"https://www.louvre.fr/en/explore/visitor-trails/the-louvre-s-masterpieces/romanticism-topicality-sensuality", liberty:"https://www.louvre.fr/en/explore/visitor-trails/the-louvre-s-masterpieces/romanticism-topicality-sensuality",
  hammurabi:"https://www.louvre.fr/en/the-code-of-hammurabi", lamassu:"https://www.louvre.fr/en/explore/the-palace/the-palace-of-sargon-ii", sphinx:"https://www.louvre.fr/en/explore/the-palace/the-guardian-of-egyptian-art", scribe:"https://www.louvre.fr/en/explore/the-palace/the-guardian-of-egyptian-art",
  psyche:"https://www.louvre.fr/en/explore/visitor-trails/the-louvre-s-masterpieces/bringing-marble-to-life", hermaphroditus:"https://collections.louvre.fr/en/ark:/53355/cl010250571", diana:"https://www.louvre.fr/en/explore/the-palace/at-the-heart-of-the-renaissance-palace",
  slaves:"https://www.louvre.fr/en/explore/visitor-trails/the-louvre-s-masterpieces/imprisoned-in-stone", anne:"https://www.louvre.fr/en/explore/visitor-trails/the-louvre-s-masterpieces/treasures-of-the-italian-renaissance", odalisque:"https://collections.louvre.fr/ark:/53355/cl010065566",
  botticelli:"https://www.louvre.fr/en/explore/visitor-trails/the-louvre-s-masterpieces/italian-frescoes-on-the-walls-of-the-louvre", basin:"https://www.louvre.fr/en/explore/the-palace/an-introduction-to-islamic-art", regent:"https://www.louvre.fr/en/explore/the-palace/sun-gold-and-diamonds"
};

const louvreImportance = {
  victory:["稀世珍品","少数能把大型希腊化原作、船首基座、圣所位置与特定观看角度共同保存的胜利女神像；目前可明确比较的另一件大型原作是奥林匹亚的派奥尼奥斯胜利女神。"],
  venus:["稀世珍品","少数保存至今、接近真人尺度且完成度极高的古希腊大理石女神像；残缺双臂没有破坏躯干旋转与衣褶结构。"],
  mona:["稀世珍品","达·芬奇公认存世绘画极少；这件成熟原作集中保存晕涂法、难以固定的表情和人物与风景之间的连续空气。"],
  cana:["重要藏品","卢浮宫体量最大的绘画之一，也是委罗内塞大型威尼斯宴会画的代表作；原为修道院餐厅量身创作。"],
  coronation:["重要藏品","拿破仑政权委托、大卫主动调整人物与事实的巨幅官方图像，是权力编辑自身记忆的第一手视觉证据。"],
  raft:["重要藏品","席里柯把当时的海难与政治丑闻提升为传统历史画尺寸，是法国浪漫主义和新闻事件进入纪念碑绘画的关键转折。"],
  liberty:["稀世珍品","法国浪漫主义与现代政治图像中最具辨识度的原作之一，把真实街垒、古典寓意和普通市民压进同一画面。"],
  hammurabi:["稀世珍品","不是最早法律文本，却是保存最完整、影响最大的一批古代近东法律纪念碑之一；近三百条判例与神授王权图像同在。"],
  lamassu:["稀世珍品","成对守卫萨尔贡二世宫殿入口的巨型亚述雕刻，以原尺度、铭文和五腿观看机制保存建筑功能。"],
  sphinx:["重要藏品","现存体量最大的埃及境外狮身人面像之一；跨时代铭文让同一雕像成为王权反复占用和改写的载体。"],
  scribe:["重要藏品","古王国时期保存如此鲜活眼神、彩绘皮肤和个体化身体的书记像非常少见。"],
  psyche:["重要藏品","卡诺瓦新古典主义最具代表性的群像之一；两具身体、翅膀和手臂构成必须绕行才能读完的开放结构。"],
  hermaphroditus:["重要藏品","古罗马雕像与贝尼尼十七世纪床垫组成跨时代整体，观看顺序本身参与揭示作品主题。"],
  diana:["重要藏品","罗马时代大理石像保存著名古希腊狩猎女神类型，又经历法国王室收藏和凡尔赛陈列。"],
  slaves:["重要藏品","来自教皇尤利乌斯二世陵墓这一反复修改的计划；完成与未完成表面同时保存米开朗基罗的雕刻过程。"],
  anne:["重要藏品","达·芬奇极少数成熟存世绘画之一，以连续旋转的身体链条和晕涂法组织三代人物关系。"],
  odalisque:["重要藏品","安格尔主动拉长人体以服从背部曲线，是理解十九世纪古典主义、东方主义与现代身体观看的重要原作。"],
  botticelli:["重要藏品","从佛罗伦萨别墅墙面转移保存的罕见世俗壁画，古典女神、婚礼赠礼与原有室内功能相连。"],
  basin:["稀世珍品","十四世纪马穆鲁克金银错嵌金属器的世界级代表；后来的法国洗礼盆名称同时保存了欧洲再解释它的历史。"],
  regent:["重要藏品","超过 140 克拉的历史钻石，以切割质量和连续进入法国王室及国家象征物的经历著称。"]
};

const louvreCoreWorks = [
  {id:"victory",ch:"fame",zh:"萨莫色雷斯的胜利女神",en:"Winged Victory of Samothrace",by:"古希腊雕刻家，作者不详",date:"约公元前 190 年",place:"德农馆 · 达鲁楼梯",tag:"绝对不可错过",cardSummary:"站到左前方，看她怎样迎风降落。",time:"5 分钟"},
  {id:"venus",ch:"fame",zh:"米洛的维纳斯",en:"Venus de Milo",by:"古希腊雕刻家，作者不详",date:"约公元前 130—100 年",place:"叙利馆 · 古希腊雕塑展区；位置需核验",tag:"绝对不可错过",cardSummary:"先别替她补手，看身体怎样旋转。",time:"3 分钟"},
  {id:"mona",ch:"fame",zh:"蒙娜丽莎",en:"Mona Lisa",by:"列奥纳多·达·芬奇",date:"约 1503—1519 年",place:"德农馆 · 711 展厅",tag:"绝对不可错过",cardSummary:"先看她有多小，再看人群有多大。",time:"排队不定"},
  {id:"cana",ch:"fame",zh:"加纳的婚宴",en:"The Wedding Feast at Cana",by:"保罗·委罗内塞",date:"1562—1563 年",place:"德农馆 · 711 展厅",tag:"绝对不可错过",cardSummary:"从《蒙娜丽莎》前转身，先看尺寸反差。",time:"3 分钟"},
  {id:"coronation",ch:"nation",zh:"拿破仑一世加冕大典",en:"The Coronation of Napoleon",by:"雅克-路易·大卫",date:"1806—1807 年",place:"德农馆 · 法国绘画展区；位置需核验",tag:"强烈推荐",cardSummary:"找出那个实际上没有出席的人。",time:"4 分钟"},
  {id:"raft",ch:"nation",zh:"梅杜萨之筏",en:"The Raft of the Medusa",by:"泰奥多尔·席里柯",date:"1818—1819 年",place:"德农馆 · 700 展厅；位置需核验",tag:"绝对不可错过",cardSummary:"沿尸体形成的斜线寻找远船。",time:"5 分钟"},
  {id:"liberty",ch:"nation",zh:"自由引导人民",en:"Liberty Leading the People",by:"欧仁·德拉克洛瓦",date:"1830 年",place:"德农馆 · 700 展厅；位置需核验",tag:"绝对不可错过",cardSummary:"先确认：这不是 1789 年。",time:"4 分钟"},
  {id:"hammurabi",ch:"power",zh:"汉谟拉比法典石碑",en:"The Code of Hammurabi",by:"古巴比伦工匠，作者不详",date:"约公元前 1750 年",place:"黎塞留馆 · 近东古代艺术展区；位置需核验",tag:"绝对不可错过",cardSummary:"先抬头看神，再低头看法律。",time:"4 分钟"},
  {id:"lamassu",ch:"power",zh:"科萨巴德人首翼牛",en:"Human-Headed Winged Bull",by:"新亚述宫廷工匠",date:"约公元前 721—705 年",place:"黎塞留馆 · 科萨巴德庭院",tag:"强烈推荐",cardSummary:"从正面和侧面各数一次腿。",time:"3 分钟"},
  {id:"sphinx",ch:"power",zh:"塔尼斯大狮身人面像",en:"Great Sphinx of Tanis",by:"古埃及雕刻家，作者不详",date:"约公元前 2600 年，后世多次重刻",place:"叙利馆 · 埃及古代艺术展区；位置需核验",tag:"强烈推荐",cardSummary:"退后，看它怎样守住入口。",time:"3 分钟"},
  {id:"scribe",ch:"power",zh:"书记坐像",en:"The Seated Scribe",by:"古埃及雕刻家，作者不详",date:"约公元前 2620—2500 年",place:"叙利馆 · 埃及古代艺术展区；位置需核验",tag:"强烈推荐",cardSummary:"蹲低一点，让视线与他齐平。",time:"3 分钟"},
  {id:"psyche",ch:"stone",zh:"丘比特之吻唤醒普赛克",en:"Psyche Revived by Cupid's Kiss",by:"安东尼奥·卡诺瓦",date:"1787—1793 年",place:"德农馆 · 欧洲雕塑展区；位置需核验",tag:"绝对不可错过",cardSummary:"绕一圈，别只拍接吻角度。",time:"4 分钟"},
  {id:"hermaphroditus",ch:"stone",zh:"沉睡的赫尔玛佛洛狄忒斯",en:"Sleeping Hermaphroditus",by:"古罗马雕刻家；床垫由贝尼尼制作",date:"雕像约公元 2 世纪；床垫 1620 年",place:"叙利馆 · 古希腊罗马雕塑展区；位置需核验",tag:"强烈推荐",cardSummary:"从背面接近，再慢慢绕到正面。",time:"3 分钟"},
  {id:"diana",ch:"stone",zh:"凡尔赛的狄安娜",en:"Diana of Versailles",by:"古罗马雕刻家，依希腊原作",date:"约公元 1—2 世纪",place:"叙利馆 · 古希腊罗马雕塑展区；位置需核验",tag:"强烈推荐",cardSummary:"从迈出的腿开始追踪动作。",time:"3 分钟"},
  {id:"slaves",ch:"stone",zh:"垂死的奴隶与反抗的奴隶",en:"Dying & Rebellious Slaves",by:"米开朗基罗",date:"1513—1516 年",place:"德农馆 · 米开朗基罗画廊；当前不可见",tag:"当前不可见",cardSummary:"比较沉睡与反抗两种身体。",time:"未展出",unavailable:true},
  {id:"anne",ch:"gaze",zh:"圣安妮、圣母与圣婴",en:"Saint Anne, the Virgin and Child",by:"列奥纳多·达·芬奇",date:"约 1503—1519 年",place:"德农馆 · 意大利绘画展区；位置需核验",tag:"强烈推荐",cardSummary:"沿三个人的头部找旋转链条。",time:"4 分钟"},
  {id:"odalisque",ch:"gaze",zh:"大宫女",en:"Grande Odalisque",by:"让-奥古斯特-多米尼克·安格尔",date:"1814 年",place:"德农馆 · 法国绘画展区；位置需核验",tag:"强烈推荐",cardSummary:"沿过长的背部走一遍。",time:"3 分钟"},
  {id:"botticelli",ch:"gaze",zh:"维纳斯与三美神向少女献礼",en:"Venus and the Three Graces",by:"桑德罗·波提切利",date:"约 1483—1486 年",place:"德农馆 · 意大利绘画展区；位置需核验",tag:"强烈推荐",cardSummary:"先看壁画与墙面的边界。",time:"3 分钟"},
  {id:"basin",ch:"afterlife",zh:"圣路易洗礼盆",en:"Baptistery of Saint Louis",by:"穆罕默德·伊本·扎因",date:"约 1320—1340 年",place:"伊斯兰艺术部；当前展区关闭",tag:"当前不可见",cardSummary:"别被后来的法国名称带走。",time:"展区关闭",unavailable:true},
  {id:"regent",ch:"afterlife",zh:"摄政王钻石",en:"The Regent Diamond",by:"切割师不详；钻石出产于印度",date:"约 1698—1700 年切割",place:"阿波罗画廊；当前关闭",tag:"当前不可见",cardSummary:"看它被不同政权装在了哪里。",time:"展厅关闭",unavailable:true}
].map(work=>({...work,editorialRole:"第一次先看",significance:louvreImportance[work.id][0],preciousWhy:louvreImportance[work.id][1],image:commonsImage(louvreImages[work.id]),imageSource:commonsSource(louvreImages[work.id]),source:louvreSources[work.id]}));

const louvreExpansionWorks = [
  {id:"medieval-louvre",ch:"palace",zh:"中世纪卢浮宫城壕与地基",en:"The Medieval Louvre",by:"腓力二世时期的王室建筑工程",date:"约 1190 年起",place:"叙利馆 · 地下 1 层；维修开放状态需核验",tag:"继续看懂",cardSummary:"先别把卢浮宫想成宫殿：它最早是一座城防堡垒。",time:"6 分钟",unavailable:true,significance:"特色看点",preciousWhy:"卢浮宫仍可在原址步行穿过约 1190 年堡垒的城壕与城墙遗存；价值不在孤立石块，而在八百年建筑层累仍嵌于今日博物馆地下。",image:"https://upload.wikimedia.org/wikipedia/commons/f/f9/Corner_of_the_ditches_of_the_medieval_Louvre_2.jpg",imageSource:"https://commons.wikimedia.org/wiki/File:Corner_of_the_ditches_of_the_medieval_Louvre_2.jpg",source:"https://www.louvre.fr/en/visit/accessibility/visitors-with-visual-impairments"},
  {id:"caryatides",ch:"palace",zh:"女像柱厅",en:"Salle des Caryatides",by:"建筑：皮埃尔·莱斯科；雕刻：让·古戎",date:"1546 年起；女像柱约 1550 年",place:"叙利馆 · 348 展厅",tag:"继续看懂",cardSummary:"抬头找乐师台：这间古雕塑展厅原本是一座王室舞厅。",time:"5 分钟",significance:"重要藏品",preciousWhy:"它把法国文艺复兴王宫建筑、让·古戎的四尊承重女像柱和 1692 年以来的王室古代雕塑陈列叠在同一房间，是卢浮宫由宫殿转为博物馆的实体证据。",image:"https://api-www.louvre.fr/sites/default/files/2021-02/la-salle-des-cariatides-vue-sur-la-diane-de-versailles.jpg",imageSource:"https://www.louvre.fr/en/explore/the-palace/at-the-heart-of-the-renaissance-palace",source:"https://www.louvre.fr/en/explore/the-palace/at-the-heart-of-the-renaissance-palace"},
  {id:"apollo-gallery",ch:"palace",zh:"阿波罗长廊",en:"Galerie d’Apollon",by:"夏尔·勒布伦等；17—19 世纪多位艺术家续作",date:"1661 年火灾后重建；1851 年完成",place:"德农馆 · 705 展厅；当前暂时关闭",tag:"当前不可见",cardSummary:"先看天花板，再看珠宝：法国王权把太阳、黄金和宝石压进同一条轴线。",time:"展厅关闭",unavailable:true,significance:"重要藏品",preciousWhy:"这条长廊是路易十四太阳王形象的关键室内工程，也成为凡尔赛镜厅的重要前身；今天又陈列法国王冠珠宝，把王权空间和国家藏品直接接合。",image:"https://api-www.louvre.fr/sites/default/files/2026-07/Couverture%20HD.jpg",imageSource:"https://www.louvre.fr/en/explore/the-palace/sun-gold-and-diamonds",source:"https://www.louvre.fr/en/explore/the-palace/sun-gold-and-diamonds"},
  {id:"napoleon-apartments",ch:"palace",zh:"拿破仑三世套房",en:"Napoleon III Apartments",by:"建筑与装饰：赫克托·勒菲埃尔等",date:"1858—1861 年",place:"黎塞留馆 · 1 层；开放状态需按当天核验",tag:"继续看懂",cardSummary:"名字会骗人：这里不是皇帝卧室，而是帝国政府部长用来展示权力的套房。",time:"8 分钟",significance:"特色看点",preciousWhy:"第二帝国时期的整套国家礼仪空间保存于原址，且直到 1989 年仍由法国财政部使用；它让卢浮宫“宫殿—政府机关—博物馆”的连续历史可见。",image:"https://api-www.louvre.fr/sites/default/files/2021-02/appartements-napoleon-iii-le-grand-salon.jpg",imageSource:"https://www.louvre.fr/en/explore/the-palace/the-splendour-of-the-second-empire",source:"https://www.louvre.fr/en/explore/the-palace/the-splendour-of-the-second-empire"},
  {id:"five-continents",ch:"palace",zh:"五大洲展厅",en:"Gallery of Five Continents",by:"2025 年展陈设计：让-米歇尔·维尔莫特",date:"建筑属第二帝国；2025 年改陈",place:"德农馆 · 塞纳河一侧",tag:"继续看懂",cardSummary:"这不是“卢浮宫又多收了一洲”，而是它公开重写自己展示世界的方式。",time:"8 分钟",significance:"特色看点",preciousWhy:"2025 年的新展陈把卢浮宫、凯布朗利、吉美、法国国家图书馆等机构的对象并置，并公开讨论它们如何进入欧洲收藏；价值在于博物馆以当代策展回应自身覆盖边界。",image:"https://api-www.louvre.fr/sites/default/files/2025-12/AE251549.jpg",imageSource:"https://www.louvre.fr/en/explore/the-palace/from-all-corners-of-the-world",source:"https://www.louvre.fr/en/explore/the-palace/from-all-corners-of-the-world"},
  {id:"marly-horses",ch:"collection",zh:"马利骏马",en:"The Marly Horses",by:"纪尧姆·库斯图",date:"1745 年",place:"黎塞留馆 · 马利庭院 102 展厅",tag:"继续看懂",cardSummary:"先绕到侧面：真正的主题不是马，而是人怎样勉强压住一股向外爆发的力。",time:"5 分钟",significance:"重要藏品",preciousWhy:"这对高约 3.4 米的卡拉拉大理石群像原为马利宫皇家园林而作，1794 年迁入巴黎、1984 年进入卢浮宫；原作、公共纪念空间与复制品替换史共同保留。",image:"https://collections.louvre.fr/media/cache/large/0000000021/0000091993/0000328309_OG.JPG",imageSource:"https://collections.louvre.fr/en/ark:/53355/cl010091993",source:"https://collections.louvre.fr/en/ark:/53355/cl010091993"},
  {id:"naram-sin",ch:"collection",zh:"纳拉姆辛胜利石碑",en:"Victory Stele of Naram-Sin",by:"阿卡德王国工匠",date:"约公元前 2254—2218 年",place:"黎塞留馆 · 228 展厅",tag:"继续看懂",cardSummary:"别从下往上读成几层队伍；沿山坡斜线追着国王往上走。",time:"5 分钟",significance:"稀世珍品",preciousWhy:"约四千二百年前的完整大型王权纪念碑，以连续山坡取代传统横向分层；它还保留了十二世纪前被埃兰王当战利品从西帕尔带到苏萨的二次铭文，是古代掠夺史也写在对象上的少见实例。",image:"https://collections.louvre.fr/media/cache/large/0000000021/0000123450/0000229069_OG.JPG",imageSource:"https://collections.louvre.fr/en/ark:/53355/cl010123450",source:"https://collections.louvre.fr/en/ark:/53355/cl010123450"},
  {id:"darius-archers",ch:"collection",zh:"大流士宫弓箭手饰带",en:"Frieze of Archers from the Palace of Darius I",by:"阿契美尼德波斯宫廷工匠",date:"约公元前 522—486 年",place:"叙利馆 · 307 展厅",tag:"继续看懂",cardSummary:"先看四个人有多像，再找每块釉砖怎样把“完全一样”拆成手工差异。",time:"4 分钟",significance:"重要藏品",preciousWhy:"高约 4.75 米的成组彩釉硅质砖饰带来自苏萨大流士一世宫殿，保留阿契美尼德建筑用重复队列、强烈色彩和三语铭文制造帝国秩序的方式。",image:"https://collections.louvre.fr/media/cache/large/0000000021/0000170854/0000225449_OG.JPG",imageSource:"https://collections.louvre.fr/en/ark:/53355/cl010170854",source:"https://collections.louvre.fr/en/ark:/53355/cl010170854"},
  {id:"ebih-il",ch:"collection",zh:"埃比赫·伊尔坐像",en:"Statue of Ebih-Il",by:"马里城工匠",date:"约公元前 2400 年",place:"黎塞留馆 · 234 展厅",tag:"继续看懂",cardSummary:"先蹲低看他的眼睛：虔敬不是抽象表情，而是一套昂贵材料制造出的持续注视。",time:"4 分钟",significance:"稀世珍品",preciousWhy:"52.5 厘米高的早王朝祈祷者像保留雪花石膏身体、贝壳与青金石眼睛、沥青黏合和带名铭文；1934 年出土于马里伊什塔尔神庙后按发掘分配进入卢浮宫。",image:"https://collections.louvre.fr/media/cache/large/0000000021/0000120528/0000326137_OG.JPG",imageSource:"https://collections.louvre.fr/en/ark:/53355/cl010120528",source:"https://collections.louvre.fr/en/ark:/53355/cl010120528"},
  {id:"dendera-zodiac",ch:"collection",zh:"丹德拉黄道十二宫",en:"Dendera Zodiac",by:"托勒密时期埃及工匠",date:"公元前 50 年夏",place:"叙利馆 · 325 展厅",tag:"继续看懂",cardSummary:"先找圆盘四周托举天空的手臂，再找你熟悉的星座怎样被埃及形象包围。",time:"5 分钟",significance:"稀世珍品",preciousWhy:"它是保留具体神庙位置与公元前 50 年年代依据的圆形天象浮雕；1821 年经许可从丹德拉哈索尔神庙屋顶拆下运往法国，既是天文学图像，也是不可回避的建筑移除史。",image:"https://collections.louvre.fr/media/cache/large/0000000021/0000028871/0000068579_OG.JPG",imageSource:"https://collections.louvre.fr/en/ark:/53355/cl010028871",source:"https://collections.louvre.fr/en/ark:/53355/cl010028871"},
  {id:"spouses-sarcophagus",ch:"collection",zh:"夫妻石棺",en:"Sarcophagus of the Spouses",by:"伊特鲁里亚工匠",date:"约公元前 520—510 年",place:"叙利馆 · 663 展厅",tag:"继续看懂",cardSummary:"别先看“夫妻恩爱”；看两具身体怎样共用一张宴席床，又怎样留出消失的手中物。",time:"5 分钟",significance:"重要藏品",preciousWhy:"这件长约 1.9 米的彩绘陶棺来自切尔韦泰，以两个大型烧制部分组合成人体群像；罗马朱莉亚别墅另藏一件著名近似例，说明它不是孤例，但两件都属于罕见的大型伊特鲁里亚丧葬群像。",image:"https://collections.louvre.fr/media/cache/large/0000000021/0000298047/0000627421_OG.JPG",imageSource:"https://collections.louvre.fr/en/ark:/53355/cl010298047",source:"https://collections.louvre.fr/en/ark:/53355/cl010298047"},
  {id:"al-mughira",ch:"collection",zh:"穆吉拉王子象牙盒",en:"Pyxis of al-Mughira",by:"后倭马亚宫廷工匠",date:"968 年",place:"长期借展于阿布扎比卢浮宫，至 2027-07-31",tag:"当前不可见",cardSummary:"先别把密密麻麻的动物当装饰：这只小盒子可能在用图像谈继承与权力。",time:"馆外借展",unavailable:true,significance:"稀世珍品",preciousWhy:"作品以完整阿拉伯铭文点名哈里发之子穆吉拉并精确纪年 968 年；18 厘米高的象牙圆盒把宫廷人物、动物与植物压进连续雕刻，是科尔多瓦哈里发宫廷象牙器最重要的有纪年实例之一。",image:"https://collections.louvre.fr/media/cache/large/0000000021/0000329109/0000660837_OG.JPG",imageSource:"https://collections.louvre.fr/en/ark:/53355/cl010329109",source:"https://collections.louvre.fr/en/ark:/53355/cl010329109"},
  {id:"jeanne-virgin",ch:"collection",zh:"让娜·德夫勒圣母子像",en:"Virgin and Child of Jeanne d’Evreux",by:"巴黎金银匠，作者不详",date:"1324—1339 年",place:"黎塞留馆 · 503 展厅",tag:"继续看懂",cardSummary:"先看圣母身体弯成的 S 形，再看底座小场景：私人礼物怎样变成王室、修道院与国家之间的对象。",time:"5 分钟",significance:"稀世珍品",preciousWhy:"高 68 厘米、重约 10 公斤的鎏金银圣母像仍保留珐琅、珍珠、宝石与水晶；王后 1339 年赠予圣但尼修道院，1793 年革命接收进入博物馆，来源链条异常完整。",image:"https://collections.louvre.fr/media/cache/original/0000000021/0000096615/0000835636_OG.JPG",imageSource:"https://collections.louvre.fr/en/ark:/53355/cl010096615",source:"https://collections.louvre.fr/en/ark:/53355/cl010096615"},
  {id:"barberini-ivory",ch:"collection",zh:"巴贝里尼象牙板",en:"Barberini Ivory",by:"东罗马帝国工匠",date:"约 525—550 年",place:"黎塞留馆 · 501 展厅",tag:"继续看懂",cardSummary:"先看中央皇帝有多大，再看脚下异族、上方基督和侧边胜利女神怎样替他搭起宇宙秩序。",time:"5 分钟",significance:"稀世珍品",preciousWhy:"大型五联象牙板仍保存中央皇帝骑马凯旋及四周政治—宗教层级，是六世纪东罗马帝国象牙外交礼物中保存最完整、讨论最集中的实例之一；皇帝是否就是查士丁尼仍有争议。",image:"https://collections.louvre.fr/media/cache/large/0000000021/0000114082/0000247488_OG.JPG",imageSource:"https://collections.louvre.fr/en/ark:/53355/cl010114082",source:"https://collections.louvre.fr/en/ark:/53355/cl010114082"},
  {id:"lacemaker",ch:"collection",zh:"花边女工",en:"The Lacemaker",by:"约翰内斯·维米尔",date:"约 1669—1670 年",place:"黎塞留馆 · 837 展厅",tag:"继续看懂",cardSummary:"先看她的手，再看前景两缕红线：维米尔把最清楚的劳动和最模糊的颜料放在一起。",time:"5 分钟",significance:"稀世珍品",preciousWhy:"维米尔公认存世作品仅约三十余件；这件小幅原作又有从其主要赞助人范·勒伊文家族到 1870 年卢浮宫购入的可追踪来源，是理解其光学模糊与专注人物的核心实例。",image:"https://collections.louvre.fr/media/cache/large/0000000021/0000064918/0000134402_OG.JPG",imageSource:"https://collections.louvre.fr/en/ark:/53355/cl010064918",source:"https://collections.louvre.fr/en/ark:/53355/cl010064918"},
  {id:"money-changer",ch:"collection",zh:"放贷人与他的妻子",en:"The Money Changer and His Wife",by:"昆廷·马赛斯",date:"1514 年",place:"黎塞留馆 · 814 展厅",tag:"继续看懂",cardSummary:"先看妻子的眼睛：她读着祈祷书，视线却被丈夫手里的金币吸走。",time:"4 分钟",significance:"重要藏品",preciousWhy:"1514 年签名原作把宗教书、秤、硬币与凸面镜组织成道德和职业现实的双重观看；1806 年由卢浮宫购入，是早期尼德兰世俗风俗画转型的关键作品。",image:"https://collections.louvre.fr/media/cache/large/0000000021/0000061690/0000340373_OG.JPG",imageSource:"https://collections.louvre.fr/en/ark:/53355/cl010061690",source:"https://collections.louvre.fr/en/ark:/53355/cl010061690"},
  {id:"cheat",ch:"collection",zh:"方块 A 作弊者",en:"The Cheat with the Ace of Diamonds",by:"乔治·德·拉图尔",date:"约 1636—1640 年",place:"叙利馆 · 912 展厅",tag:"继续看懂",cardSummary:"别先找牌；沿四个人的眼神走一圈，你会在受害者发现以前加入骗局。",time:"5 分钟",significance:"重要藏品",preciousWhy:"拉图尔同题有两件直接版本，另一件藏于金贝尔艺术博物馆；X 光显示卢浮宫版本修改了女仆位置与衣色，因而不只是重复，而是能研究艺术家如何重组骗局节奏的后出版本。",image:"https://collections.louvre.fr/media/cache/large/0000000021/0000066276/0000403278_OG.JPG",imageSource:"https://collections.louvre.fr/en/ark:/53355/cl010066276",source:"https://collections.louvre.fr/en/ark:/53355/cl010066276"},
  {id:"pierrot",ch:"collection",zh:"皮埃罗（旧称《吉尔》）",en:"Pierrot (formerly Gilles)",by:"让-安托万·华托",date:"约 1718—1719 年",place:"叙利馆 · 917 展厅",tag:"继续看懂",cardSummary:"先忽略后面那群戏班人物，只看白衣人为什么像被推到台前，却不知道下一句台词。",time:"5 分钟",significance:"重要藏品",preciousWhy:"约 1.84 米高的人物远超华托常见小幅雅宴画尺度，主题、用途与原委托均未确定；作品经德农收藏、拉卡兹收藏，于 1869 年遗赠卢浮宫，收藏家共同塑造了法国绘画馆藏。",image:"https://collections.louvre.fr/media/cache/large/0000000021/0000059617/0001280888_OG.JPG",imageSource:"https://collections.louvre.fr/en/ark:/53355/cl010059617",source:"https://collections.louvre.fr/en/ark:/53355/cl010059617"},
  {id:"clubfoot",ch:"collection",zh:"跛足少年",en:"The Clubfoot",by:"胡塞佩·德·里贝拉",date:"1642 年",place:"德农馆 · 718 展厅",tag:"继续看懂",cardSummary:"先看他的笑，再读他手里的纸：画面让你仰视一个当时通常被俯视的人。",time:"5 分钟",significance:"重要藏品",preciousWhy:"1642 年签名并纪年的真人尺度肖像，以极低视点把携带乞讨说明的残障少年推向天空；1869 年拉卡兹遗赠使它进入卢浮宫，也代表私人收藏如何补强西班牙绘画。",image:"https://collections.louvre.fr/media/cache/large/0000000021/0000059547/0001179049_OG.JPG",imageSource:"https://collections.louvre.fr/en/ark:/53355/cl010059547",source:"https://collections.louvre.fr/en/ark:/53355/cl010059547"},
  {id:"louis-xv-crown",ch:"collection",zh:"路易十五私人王冠",en:"Personal Crown of Louis XV",by:"克洛德·龙代设计；奥古斯坦·迪弗洛等制作",date:"1722 年",place:"当前未展出",tag:"当前不可见",cardSummary:"别把闪亮程度当真：原宝石早被换走，留下的正是王权怎样被拆解、保存和再陈列的证据。",time:"未展出",unavailable:true,significance:"稀世珍品",preciousWhy:"1722 年加冕礼制作的两顶王冠中，这顶银鎏金宝石冠得以保存；原宝石 1729 年后被替换，王冠又经历 1793 年革命接收和 1852 年主权者博物馆陈列，物质替换与制度变迁都有明确记录。",image:"https://collections.louvre.fr/media/cache/large/0000000021/0000097015/0000235462_OG.JPG",imageSource:"https://collections.louvre.fr/en/ark:/53355/cl010097015",source:"https://collections.louvre.fr/en/ark:/53355/cl010097015"}
].map(work=>({...work,editorialRole:"继续看懂"}));

const louvreNewWorks = [
  {id:"virgin-rocks",zh:"岩间圣母",en:"The Virgin of the Rocks",by:"列奥纳多·达·芬奇",date:"约 1483—1494 年",place:"德农馆 · 710 展厅",tag:"强烈推荐",cardSummary:"先别数人物，沿四只手看一套没有文字的指挥系统。",time:"5 分钟",significance:"稀世珍品",preciousWhy:"达·芬奇成熟期存世绘画极少；此作与伦敦国家美术馆版本构成最直接的一组同题比较，委托纠纷、两个版本与复杂转移历史都能落实到具体材料和构图差异。",image:"https://collections.louvre.fr/media/cache/large/0000000021/0000062373/0000855957_OG.JPG",imageSource:"https://collections.louvre.fr/ark:/53355/cl010062373",source:"https://collections.louvre.fr/ark:/53355/cl010062373"},
  {id:"vultures-stele",zh:"兀鹫碑",en:"Stele of the Vultures",by:"苏美尔拉格什工匠",date:"约公元前 2450—2425 年",place:"黎塞留馆 · 236 展厅",tag:"强烈推荐",cardSummary:"先看整齐军阵，再看兀鹫嘴里叼着什么：胜利在这里既是秩序也是尸体。",time:"5 分钟",significance:"稀世珍品",preciousWhy:"它是现存最早一批把具体战争、国王、军阵、尸体与文字叙事合在同一纪念碑上的大型作品；七块残片来自不同发掘批次，其中一片1933年由大英博物馆转让，现代拼合史也可追踪。",image:"https://collections.louvre.fr/media/cache/large/0000000021/0000121794/0001307742_OG.JPG",imageSource:"https://collections.louvre.fr/ark:/53355/cl010121794",source:"https://collections.louvre.fr/ark:/53355/cl010121794"},
  {id:"san-romano",zh:"圣罗马诺之战",en:"The Battle of San Romano",by:"保罗·乌切洛",date:"约 1450—1475 年",place:"德农馆 · 708 展厅",tag:"强烈推荐",cardSummary:"先看地上的断枪：它们不是战场垃圾，而是画家铺设透视的标尺。",time:"5 分钟",significance:"稀世珍品",preciousWhy:"这是一组三联战役画仅存的三块原板之一，另外两块分藏伦敦国家美术馆和佛罗伦萨乌菲齐；三件早已分离，卢浮宫这一板保留乌切洛用兵器、马匹和缩短法把战争变成透视实验的关键一段。",image:"https://collections.louvre.fr/media/cache/large/0000000021/0000065339/0000134050_OG.JPG",imageSource:"https://collections.louvre.fr/ark:/53355/cl010065339",source:"https://collections.louvre.fr/ark:/53355/cl010065339"},
  {id:"horatii",zh:"贺拉斯兄弟之誓",en:"The Oath of the Horatii",by:"雅克-路易·大卫",date:"1784 年",place:"德农馆 · 702 展厅",tag:"强烈推荐",cardSummary:"先沿三把剑看向三条伸直的手臂，再转向右侧塌下去的身体。",time:"5 分钟",significance:"稀世珍品",preciousWhy:"大卫受路易十六王室委托，却自行改变题目并扩大画幅；这件1785年沙龙原作把新古典主义的线性纪律、公共义务和私人痛苦压进一套后来影响深远的历史画结构。",image:"https://collections.louvre.fr/media/cache/large/0000000021/0000062239/0000846222_OG.JPG",imageSource:"https://collections.louvre.fr/ark:/53355/cl010062239",source:"https://collections.louvre.fr/ark:/53355/cl010062239"},
  {id:"sardanapalus",zh:"萨达纳帕勒之死",en:"The Death of Sardanapalus",by:"欧仁·德拉克洛瓦",date:"1827 年",place:"德农馆 · 700 展厅",tag:"强烈推荐",cardSummary:"别急着找故事顺序：先看白床怎样像斜坡，把人物、珠宝和马一起冲向左下角。",time:"5 分钟",significance:"重要藏品",preciousWhy:"近五米宽的沙龙原作在1828年遭遇严厉批评，画家十八年未能售出；它以色彩、斜线和拥挤身体反驳学院式清晰叙事，是德拉克洛瓦与法国浪漫主义的重要转折。",image:"https://collections.louvre.fr/media/cache/large/0000000021/0000065757/0001224148_OG.JPG",imageSource:"https://collections.louvre.fr/ark:/53355/cl010065757",source:"https://collections.louvre.fr/ark:/53355/cl010065757"},
  {id:"amun-tutankhamun",zh:"阿蒙保护图坦卡蒙像",en:"Amun Protecting Tutankhamun",by:"古埃及宫廷工匠",date:"约公元前 1330—1320 年",place:"叙利馆 · 324 展厅",tag:"强烈推荐",cardSummary:"先找那双仍搭在空气里的手：国王被抹掉以后，保护动作反而更清楚。",time:"4 分钟",significance:"重要藏品",preciousWhy:"神像大体保存，而原本站在其前的图坦卡蒙几乎被完全凿除；残缺不是泛泛的时间痕迹，而是阿玛尔纳时代之后王名、神权与政治记忆被主动修改的实体证据。",image:"https://collections.louvre.fr/media/cache/large/0000000021/0000025807/0000063459_OG.JPG",imageSource:"https://collections.louvre.fr/ark:/53355/cl010025807",source:"https://collections.louvre.fr/ark:/53355/cl010025807"},
  {id:"akhethotep",zh:"阿赫特霍特普墓室礼拜堂",en:"Mastaba Chapel of Akhethotep",by:"古埃及墓葬工匠",date:"约公元前 2490—2432 年",place:"叙利馆 · 333 展厅",tag:"强烈推荐",cardSummary:"别把墙面当连续漫画；先找那扇通向来世、实际上打不开的假门。",time:"6 分钟",significance:"稀世珍品",preciousWhy:"卢浮宫保存并重建的是萨卡拉一座古王国马斯塔巴的石砌礼拜堂，而非几块孤立浮雕；假门、供品与日常生产场景仍按墓室空间共同运作，可与原址和现代拆移史一起理解。",image:"https://collections.louvre.fr/media/cache/large/0000000021/0000077681/0001122866_OG.JPG",imageSource:"https://collections.louvre.fr/ark:/53355/cl010077681",source:"https://collections.louvre.fr/ark:/53355/cl010077681"},
  {id:"paser-coffin",zh:"帕塞尔人形棺",en:"Anthropoid Coffin of Paser",by:"古埃及棺木工匠",date:"约公元前 1069—943 年",place:"叙利馆 · 321 展厅",tag:"强烈推荐",cardSummary:"从胸口一路看到脚端：棺盖不是装饰面，而是一张把死者包进宇宙秩序的地图。",time:"5 分钟",significance:"重要藏品",preciousWhy:"长约2.6米的木棺保存第二十一王朝复杂彩绘与清漆，且铭文点出帕塞尔的多项阿蒙神职；它不是匿名的“埃及棺材”，而是能把职业、保护图像和来世结构连回具体个人的完整对象。",image:"https://collections.louvre.fr/media/cache/large/0000000021/0000028168/0000376895_OG.JPG",imageSource:"https://collections.louvre.fr/ark:/53355/cl010028168",source:"https://collections.louvre.fr/ark:/53355/cl010028168"},
  {id:"death-virgin",zh:"圣母之死",en:"The Death of the Virgin",by:"卡拉瓦乔",date:"约 1601—1606 年",place:"德农馆 · 712 展厅",tag:"强烈推荐",cardSummary:"先看那双赤脚，再看使徒怎样围出一个没有神迹光圈的真实死亡现场。",time:"5 分钟",significance:"稀世珍品",preciousWhy:"这是卡拉瓦乔少数仍可追踪原委托、拒收与连续王室收藏史的大型祭坛画；1606年被罗马教堂拒绝后，经贡扎加、英王查理一世和雅巴赫收藏，1671年进入路易十四收藏。",image:"https://collections.louvre.fr/media/cache/large/0000000021/0000062304/0000787096_OG.JPG",imageSource:"https://collections.louvre.fr/ark:/53355/cl010062304",source:"https://collections.louvre.fr/ark:/53355/cl010062304"},
  {id:"auxerre-lady",zh:"欧塞尔夫人",en:"Lady of Auxerre",by:"古希腊克里特工匠，作者不详",date:"约公元前 640—620 年",place:"德农馆 · 170 展厅",tag:"强烈推荐",cardSummary:"先看贴在胸前的大手，再找衣服上仍留下的红色：希腊雕塑原本并不洁白。",time:"4 分钟",significance:"稀世珍品",preciousWhy:"75厘米高的石灰岩像是现存极少数接近完整的代达罗斯式大型女性雕像之一，处在几何化身体向古风时期独立人像转变的关键阶段；衣纹刻线与红色痕迹还保留古代彩绘线索。",image:"https://collections.louvre.fr/media/cache/large/0000000021/0000276874/0001296200_OG.JPG",imageSource:"https://collections.louvre.fr/ark:/53355/cl010276874",source:"https://collections.louvre.fr/ark:/53355/cl010276874"},
  {id:"borghese-gladiator",zh:"博尔盖塞角斗士",en:"Borghese Gladiator",by:"以弗所的阿伽西亚斯",date:"约公元前 100 年",place:"叙利馆 · 348 展厅",tag:"强烈推荐",cardSummary:"别按名字找竞技场：顺着扭转的躯干看，他其实正挡住来自上方的攻击。",time:"4 分钟",significance:"重要藏品",preciousWhy:"真人尺度希腊化大理石原作保存雕刻家签名，并在17世纪博尔盖塞收藏中成为欧洲反复复制的古代身体范本；“角斗士”是后世命名，姿势更可能属于战斗中的武士。",image:"https://collections.louvre.fr/media/cache/large/0000000021/0000278706/0000755582_OG.JPG",imageSource:"https://collections.louvre.fr/ark:/53355/cl010278706",source:"https://collections.louvre.fr/ark:/53355/cl010278706"},
  {id:"philippe-pot",zh:"菲利普·波特墓",en:"Tomb of Philippe Pot",by:"勃艮第工坊，归于安托万·勒穆瓦蒂里耶",date:"约 1475—1500 年",place:"黎塞留馆 · 210 展厅",tag:"强烈推荐",cardSummary:"先绕到队伍侧面：八个黑衣送葬者不是围着棺材，而是在把死者抬向你。",time:"5 分钟",significance:"稀世珍品",preciousWhy:"接近原尺寸的卧像由八名独立送葬者抬举，仍保存纹章、铅饰与部分原彩，是晚期勃艮第贵族墓葬中空间结构异常完整的一件；修复替换部位也有明确记录。",image:"https://collections.louvre.fr/media/cache/large/0000000021/0000093252/0000920790_OG.JPG",imageSource:"https://collections.louvre.fr/ark:/53355/cl010093252",source:"https://collections.louvre.fr/ark:/53355/cl010093252"},
  {id:"milo-croton",zh:"克罗顿的米隆",en:"Milo of Croton",by:"皮埃尔·皮热",date:"1672—1682 年",place:"黎塞留馆 · 105 展厅",tag:"强烈推荐",cardSummary:"先看手被树缝夹住的位置，再沿扭转身体走到咬住大腿的狮口。",time:"5 分钟",significance:"重要藏品",preciousWhy:"皮热以一整块卡拉拉大理石组织树干、狮子与濒死人体，是法国巴洛克雕塑最具代表性的原作之一；它把英雄失败而非胜利做成必须绕行观看的连续动作。",image:"https://collections.louvre.fr/media/cache/large/0000000021/0000092130/0001295438_OG.JPG",imageSource:"https://collections.louvre.fr/ark:/53355/cl010092130",source:"https://collections.louvre.fr/ark:/53355/cl010092130"},
  {id:"rolin-madonna",zh:"罗兰大臣的圣母",en:"The Madonna of Chancellor Rolin",by:"扬·凡·艾克",date:"约 1430—1435 年",place:"黎塞留馆 · 818 展厅",tag:"强烈推荐",cardSummary:"先让大臣和圣母在同一高度对视，再走进他们之间那座只有手指大小的城市。",time:"5 分钟",significance:"稀世珍品",preciousWhy:"凡·艾克公认存世绘画数量有限，这件有明确委托人、革命接收史和2024年深度修复的成熟原作，又把近景肖像、建筑、微缩城市和遥远风景压在约66厘米高的木板上。",image:"https://collections.louvre.fr/media/cache/large/0000000021/0000061856/0001224211_OG.JPG",imageSource:"https://collections.louvre.fr/ark:/53355/cl010061856",source:"https://collections.louvre.fr/ark:/53355/cl010061856"},
  {id:"bathsheba",zh:"拔示巴沐浴",en:"Bathsheba at Her Bath",by:"伦勃朗",date:"1654 年",place:"黎塞留馆 · 844 展厅",tag:"强烈推荐",cardSummary:"先看她没有读出的那封信，再看下垂的手和目光怎样把身体变成一次艰难选择。",time:"5 分钟",significance:"稀世珍品",preciousWhy:"这件1654年签名原作被广泛视为伦勃朗晚期人体与心理叙事的核心作品；画家移除通常在场的偷窥国王，把整个故事压到拔示巴的身体、信件与迟疑之中。",image:"https://collections.louvre.fr/media/cache/large/0000000021/0000060453/0000388505_OG.JPG",imageSource:"https://collections.louvre.fr/ark:/53355/cl010060453",source:"https://collections.louvre.fr/ark:/53355/cl010060453"},
  {id:"castiglione",zh:"巴尔达萨雷·卡斯蒂廖内肖像",en:"Portrait of Baldassare Castiglione",by:"拉斐尔",date:"约 1514—1515 年",place:"馆方记录显示曾借展纽约；回馆状态需核验",tag:"当前不可见",cardSummary:"先看灰、黑、白怎样把服装压低，再看眼睛和嘴角怎样把一个人的克制推到前面。",time:"借展状态待核验",unavailable:true,significance:"稀世珍品",preciousWhy:"拉斐尔成熟期肖像原作以极少颜色建立近距离心理存在，且从卡斯蒂廖内家族、马扎然到路易十四的来源链可追踪；它后来成为伦勃朗、安格尔等艺术家反复临摹和回应的肖像范本。",image:"https://collections.louvre.fr/media/cache/large/0000000021/0000066418/0001179051_OG.JPG",imageSource:"https://collections.louvre.fr/ark:/53355/cl010066418",source:"https://collections.louvre.fr/ark:/53355/cl010066418"},
  {id:"pastoral-concert",zh:"田园合奏",en:"Pastoral Concert",by:"提香（传统上曾归于乔尔乔内）",date:"约 1500—1525 年",place:"馆方当前标记未展出",tag:"当前不可见",cardSummary:"先问两名裸体女人是否真的与男人处在同一个世界，再看音乐怎样把现实和诗意接起来。",time:"未展出",unavailable:true,significance:"稀世珍品",preciousWhy:"这件威尼斯文艺复兴核心原作长期在乔尔乔内与提香之间变更归属，恰好保留两人早期风格交界的难题；裸体寓意人物、乡野音乐与色彩空气后来深刻影响欧洲田园绘画。",image:"https://collections.louvre.fr/media/cache/large/0000000021/0000062281/0000561855_OG.JPG",imageSource:"https://collections.louvre.fr/ark:/53355/cl010062281",source:"https://collections.louvre.fr/ark:/53355/cl010062281"},
  {id:"cythera",zh:"舟发西苔岛",en:"Pilgrimage to Cythera",by:"让-安托万·华托",date:"1717 年",place:"叙利馆 · 917 展厅",tag:"强烈推荐",cardSummary:"别急着决定他们是登岛还是离岛；沿情侣从停留到起身的动作读时间。",time:"5 分钟",significance:"稀世珍品",preciousWhy:"这是华托1717年进入皇家绘画雕塑学院的接收作品，题材新颖到学院为它另设“雅宴画”类别；画面究竟是抵达还是离开西苔岛的歧义，来自动作和构图而非后人硬加谜语。",image:"https://collections.louvre.fr/media/cache/large/0000000021/0000061995/0000135498_OG.JPG",imageSource:"https://collections.louvre.fr/ark:/53355/cl010061995",source:"https://collections.louvre.fr/ark:/53355/cl010061995"},
  {id:"mesha-stele",zh:"梅沙石碑",en:"Mesha Stele",by:"古代摩押工匠",date:"约公元前 830—805 年",place:"叙利馆 · 303 展厅",tag:"强烈推荐",cardSummary:"先看黑色表面哪里突然变平：你看到的是原石、碎片、拓片和现代补配共同组成的文本。",time:"5 分钟",significance:"稀世珍品",preciousWhy:"34行摩押文是现存最长、最重要的一批铁器时代西北闪米特铭文之一，以摩押王自己的声音叙述对以色列的战争；原石被打碎后依靠事先制作的湿纸拓片重组，残缺机制有直接证据。",image:"https://collections.louvre.fr/media/cache/large/0000000021/0000120339/0000341988_OG.JPG",imageSource:"https://collections.louvre.fr/ark:/53355/cl010120339",source:"https://collections.louvre.fr/ark:/53355/cl010120339"},
  {id:"monzon-lion",zh:"蒙松狮",en:"Monzón Lion",by:"伊斯兰西班牙金属工匠",date:"约 975—1100 年",place:"馆方记录显示现于卢浮宫朗斯临展",tag:"当前不可见",cardSummary:"先看张开的嘴和中空身体：这只狮子原本可能不是摆件，而会让水和声音穿过身体。",time:"馆外展出",unavailable:true,significance:"重要藏品",preciousWhy:"这件约55厘米长的铸铜动物保存连续刻纹和阿拉伯祝福铭文，并可能作为喷泉出水口使用；它与比萨狮鹫等极少数大型伊斯兰金属动物构成直接比较组。",image:"https://collections.louvre.fr/media/cache/large/0000000021/0000330266/0001090965_OG.JPG",imageSource:"https://collections.louvre.fr/ark:/53355/cl010330266",source:"https://collections.louvre.fr/ark:/53355/cl010330266"},
  {id:"saint-josse-shroud",zh:"圣若斯裹尸布",en:"Shroud of Saint-Josse",by:"伊斯兰世界丝织工坊，产地仍有争议",date:"约 950—1000 年",place:"馆方当前标记未展出",tag:"当前不可见",cardSummary:"先看两只相向的大象，再想它怎样从伊斯兰宫廷织物变成法国圣人的裹尸布。",time:"未展出",unavailable:true,significance:"稀世珍品",preciousWhy:"十世纪大型丝织残片保留库法体祝福铭文和成对大象图像，后来在法国圣若斯修道院包裹圣人遗骨；同一材料跨越伊斯兰权贵语境与基督教圣物功能，存续路径异常具体。",image:"https://collections.louvre.fr/media/cache/large/0000000021/0000329960/0001090856_OG.JPG",imageSource:"https://collections.louvre.fr/ark:/53355/cl010329960",source:"https://collections.louvre.fr/ark:/53355/cl010329960"},
  {id:"gabrielle",zh:"加布里埃尔·德斯特雷与其姐妹",en:"Gabrielle d’Estrées and One of Her Sisters",by:"枫丹白露画派，作者不详",date:"约 1575—1600 年",place:"黎塞留馆 · 824 展厅",tag:"强烈推荐",cardSummary:"先别把掐乳头的手势当笑话；看戒指、缝衣女子和壁炉怎样把私人身体变成宫廷消息。",time:"4 分钟",significance:"重要藏品",preciousWhy:"作者不详并未削弱其独特性：这件法国宫廷原作以极不寻常的双人浴室肖像和手势，成为亨利四世情妇加布里埃尔·德斯特雷形象最具辨识度的一件；人物身份仍需保留判断边界。",image:"https://collections.louvre.fr/media/cache/large/0000000021/0000065402/0000720575_OG.JPG",imageSource:"https://collections.louvre.fr/ark:/53355/cl010065402",source:"https://collections.louvre.fr/ark:/53355/cl010065402"},
  {id:"ship-fools",zh:"愚人船",en:"The Ship of Fools",by:"希罗尼穆斯·博斯",date:"约 1475—1500 年",place:"黎塞留馆 · 815 展厅",tag:"强烈推荐",cardSummary:"先找船为什么没有方向：大家忙着吃喝唱歌，唯一真正向前伸出的却是一棵树。",time:"4 分钟",significance:"稀世珍品",preciousWhy:"这块博斯原作只是被拆散祭坛画的一部分，下方残片在耶鲁，相关内外翼分藏华盛顿与鹿特丹；可通过木板和图像关系具体复原原组合，残缺因此直接改变作品意义。",image:"https://collections.louvre.fr/media/cache/large/0000000021/0000062860/0000397537_OG.JPG",imageSource:"https://collections.louvre.fr/ark:/53355/cl010062860",source:"https://collections.louvre.fr/ark:/53355/cl010062860"}
].map(work=>({...work,editorialRole:"继续看懂"}));

const louvreSelection = [
  {chapter:"fame",ids:["victory","venus","mona","cana","virgin-rocks"]},
  {chapter:"history",ids:["coronation","raft","liberty","hammurabi","naram-sin","darius-archers","vultures-stele","san-romano","horatii","sardanapalus"]},
  {chapter:"belief",ids:["lamassu","sphinx","scribe","amun-tutankhamun","akhethotep","paser-coffin","dendera-zodiac","spouses-sarcophagus","jeanne-virgin","death-virgin"]},
  {chapter:"body",ids:["psyche","hermaphroditus","diana","slaves","marly-horses","auxerre-lady","borghese-gladiator","philippe-pot","milo-croton"]},
  {chapter:"gaze",ids:["anne","odalisque","botticelli","lacemaker","cheat","pierrot","rolin-madonna","bathsheba","castiglione","pastoral-concert","cythera"]},
  {chapter:"palace",ids:["basin","regent","medieval-louvre","caryatides","apollo-gallery"]},
  {chapter:"hidden",ids:["ebih-il","mesha-stele","al-mughira","barberini-ivory","monzon-lion","saint-josse-shroud","money-changer","clubfoot","gabrielle","ship-fools"]}
];

const louvreCandidateById = new Map([...louvreCoreWorks,...louvreExpansionWorks,...louvreNewWorks].map(work=>[work.id,work]));
const louvreWorks = louvreSelection.flatMap(group=>group.ids.map(id=>{
  const work = louvreCandidateById.get(id);
  if (!work) throw new Error(`卢浮宫 60 件选品缺少 ${id}`);
  return {...work,ch:group.chapter,editorialRole:group.chapter === "hidden" ? "冷门但值得" : work.editorialRole};
}));

museumData.louvre = {
  id:"louvre",city:"巴黎 · 法国",zh:"卢浮宫",en:"Musée du Louvre",...museumRatings.louvre,
  editorialCapacity:60,
  verdict:"它不只收藏名作，也制造名作。",
  hero:"https://commons.wikimedia.org/wiki/Special:FilePath/Louvre_Museum_Wikimedia_Commons_2.jpg?width=1800",
  contentFile:"./research/content/louvre.md",contentHasOverview:true,
  intro:[
    "如果你一生只去一座综合型博物馆，卢浮宫几乎一定在候选名单里。它的价值不只是明星作品，而是让人看见战争、王权、考古、市场和展陈怎样反复改写名作。",
    "它不是中性仓库：楼梯、宫殿、展厅和人群都参与作品意义。值得追问的不只是它有多有名，而是它原来是什么、为什么来到这里，以及卢浮宫怎样改变我们的观看。"
  ],
  official:"https://collections.louvre.fr/",visit:"https://www.louvre.fr/en/visit/hours-admission",chapters:louvreChapters,works:louvreWorks
};
