// Kunsthistorisches Museum Vienna — regenerated under Meowseum pipeline 2.4.8.
museumData.vienna = {
  ...museumRatings.vienna,
  ...{
  "id": "vienna",
  "editorialCapacity": 40,
  "city": "维也纳 · 奥地利",
  "zh": "维也纳艺术史博物馆",
  "en": "Kunsthistorisches Museum Vienna",
  "verdict": "",
  "hero": "https://www.khm.at/fileadmin/_processed_/f/5/csm_114_AS_SaalXI_7_AWSZ-card_59120d5a30.jpg",
  "contentFile": "./research/content/vienna.md",
  "official": "https://www.khm.at/en",
  "visit": "https://www.khm.at/en/visit",
  "cardCopyContract": "independent-v1",
  "contentUpdatedAt": "2026-07-24",
  "intro": [
    "这座馆最不可替代的地方，是多种原本服务于祭祀、法律、宴会、王朝形象和私人观看的对象，被哈布斯堡收藏汇集，再由1891年开放的专门馆舍重新编排成一部可步行进入的权力与观看史。参观从建筑的帝国序言出发，依次看权力怎样留下文字和肖像、信仰怎样进入墓室与器物、珍贵材料怎样成为宫廷技术，最后在绘画中转化为对社会、历史和绘画本身的重新组织。",
    "96分由八条独立稀世珍品线支撑，跨越勃鲁盖尔绘画群、维米尔、文艺复兴金工与青铜、宫廷水晶、罗马浮雕宝石、早期中世纪金器组及共和国法律文本。扣分来自顶级密度仍偏向哈布斯堡形成的欧洲绘画与宫廷收藏，文明跨度不及最高分综合馆；纳吉圣米克洛什宝藏为轮换状态，另有少数作品当天展出未确认。"
  ],
  "chapters": [
    {
      "id": "vienna-ch-01-building",
      "number": "01",
      "title": "为什么还没看藏品，博物馆已经开始讲权力？",
      "intro": "建立整馆最小解释模型，说明建筑不是中性容器，而是收藏公开化后的第一件解释工具。"
    },
    {
      "id": "vienna-ch-02-power",
      "number": "02",
      "title": "权力怎样把自己刻进宝石、青铜和货币？",
      "intro": "把图像宣称、法律执行、王朝配对和货币传播区分开，同时显示权力并不只存在于大型历史画。"
    },
    {
      "id": "vienna-ch-03-afterlife-story",
      "number": "03",
      "title": "一件古物怎样让死者、神话和仪式继续运作？",
      "intro": "从原始用途进入古物收藏，避免把所有古代对象只看成独立雕塑或漂亮图案。"
    },
    {
      "id": "vienna-ch-04-kunstkammer",
      "number": "04",
      "title": "当材料比用途更重要，器物会变成什么？",
      "intro": "解释艺术珍宝馆并非杂物柜，而是一套比较材料、技术、运动、古典复兴和宫廷展示的知识系统。"
    },
    {
      "id": "vienna-ch-05-bruegel",
      "number": "05",
      "title": "勃鲁盖尔怎样把一个世界压进一块画板？",
      "intro": "把本馆最强的单一画家收藏读成一组观看方法，而不是五张名作清单；《巴别塔》和《雪中猎人》共同支撑一条稀世珍品线。"
    },
    {
      "id": "vienna-ch-06-painting",
      "number": "06",
      "title": "一幅画何时不再只是再现对象？",
      "intro": "以维米尔的绘画自我指涉为核心，连接宫廷身份、文艺复兴构图、威尼斯晚期笔触、矫饰主义错觉及宗教叙事。"
    }
  ],
  "works": [
    {
      "id": "vienna-space-01-museum-building",
      "ch": "vienna-ch-01-building",
      "zh": "维也纳艺术史博物馆主馆建筑",
      "en": "Kunsthistorisches Museum Main Building",
      "by": "戈特弗里德·森佩尔 Gottfried Semper；卡尔·冯·哈森瑙尔 Carl von Hasenauer",
      "date": "1871–1891年；1891年10月17日开放",
      "material": "建筑、雕塑、绘画与展厅的整体设计",
      "place": "Maria-Theresien-Platz, Vienna · 永久建筑空间",
      "tag": "绝对不可错过",
      "significance": "重要藏品",
      "availabilityTag": "",
      "time": "贯穿主馆参观全程",
      "image": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Vienna%20-%20View%20of%20Maria%20Theresien-Platz%20and%20the%20Kunsthistorisches%20Museum%20-%206291.jpg",
      "imageSource": "https://commons.wikimedia.org/wiki/File:Vienna_-_View_of_Maria_Theresien-Platz_and_the_Kunsthistorisches_Museum_-_6291.jpg",
      "imageCaption": "维也纳艺术史博物馆主馆建筑，戈特弗里德·森佩尔 Gottfried Semper；卡尔·冯·哈森瑙尔 Carl von Hasenauer，1871–1891年；1891年10月17日开放。",
      "imageKind": "work",
      "source": "https://www.khm.at/en/exhibitions/the-kunsthistorisches-museum-gesamtkunstwerk",
      "cardSummary": "这座主馆不是收藏的中性外壳：入口、主楼梯、穹顶大厅、雕塑与绘画被组织成一件“整体艺术品”。广场对面的自然史博物馆与它外形近似，立面人物和主题却把艺术与自然分开，让一座帝国双馆如何安排知识变得可以直接观看。",
      "preciousWhy": "这座主馆不是收藏的中性外壳：入口、主楼梯、穹顶大厅、雕塑与绘画被组织成一件“整体艺术品”。广场对面的自然史博物馆与它外形近似，立面人物和主题却把艺术与自然分开，让一座帝国双馆如何安排知识变得可以直接观看。"
    },
    {
      "id": "vienna-space-02-grand-staircase-ensemble",
      "ch": "vienna-ch-01-building",
      "zh": "主楼梯整体：卡诺瓦《忒修斯战胜半人马》与楼梯绘画",
      "en": "Grand Staircase Ensemble with Canova's Theseus Slaying the Centaur",
      "by": "Antonio Canova；Mihály von Munkácsy；Hans Makart；Gustav Klimt、Ernst Klimt、Franz Matsch",
      "date": "卡诺瓦研究始于 1795 年，雕塑执行于 1810–1819 年；楼梯绘画主要完成于 1880–1891 年",
      "material": "建筑空间、大理石雕塑与楼梯绘画",
      "place": "维也纳艺术史博物馆主楼梯 · 确认在展",
      "tag": "强烈推荐",
      "significance": "体验补充",
      "availabilityTag": "",
      "time": "8–12 分钟",
      "image": "https://www.khm.at/fileadmin/img_KHM/gebaeude/innen/KHM_Stiegenhaus_052023-3559.jpg",
      "imageSource": "https://www.khm.at/en/exhibitions/the-kunsthistorisches-museum-gesamtkunstwerk",
      "imageCaption": "主楼梯整体：卡诺瓦《忒修斯战胜半人马》与楼梯绘画，Antonio Canova；Mihály von Munkácsy；Hans Makart；Gustav Klimt、Ernst Klimt、Franz Matsch，卡诺瓦研究始于 1795 年，雕塑执行于 1810–1819 年；楼梯绘画主要完成于 1880–1891 年。",
      "imageKind": "work",
      "source": "https://www.khm.at/kunstwerke/theseusgruppe-theseus-besiegt-den-kentauren-1132785",
      "cardSummary": "这座楼梯值得作为一个整体停下来：入口的克制、转折处的卡诺瓦大理石群像、头顶与四周逐渐增多的绘画，共同把上楼变成一场层层增强的入馆序曲。看似统一的装饰还藏着一段多次换手的合作史。",
      "preciousWhy": "这座楼梯值得作为一个整体停下来：入口的克制、转折处的卡诺瓦大理石群像、头顶与四周逐渐增多的绘画，共同把上楼变成一场层层增强的入馆序曲。看似统一的装饰还藏着一段多次换手的合作史。"
    },
    {
      "id": "vienna-space-03-cupola-hall",
      "ch": "vienna-ch-01-building",
      "zh": "穹顶大厅",
      "en": "Cupola Hall",
      "by": "戈特弗里德·森佩尔 Gottfried Semper；卡尔·冯·哈森瑙尔 Carl von Hasenauer 及馆舍装饰团队 · 维也纳",
      "date": "1871–1891 年",
      "material": "建筑室内与综合装饰",
      "place": "维也纳艺术史博物馆主馆中央，入口—主楼梯中轴上的永久空间",
      "tag": "强烈推荐",
      "significance": "体验补充",
      "availabilityTag": "",
      "time": "5–8 分钟",
      "image": "https://www.khm.at/fileadmin/img_KHM/gebaeude/innen/KHM_Kuppelhalle_AU_04.jpg",
      "imageSource": "https://www.khm.at/en/exhibitions/the-kunsthistorisches-museum-gesamtkunstwerk",
      "imageCaption": "穹顶大厅，戈特弗里德·森佩尔 Gottfried Semper；卡尔·冯·哈森瑙尔 Carl von Hasenauer 及馆舍装饰团队 · 维也纳，1871–1891 年。",
      "imageKind": "work",
      "source": "https://www.khm.at/en/exhibitions/the-kunsthistorisches-museum-gesamtkunstwerk",
      "cardSummary": "这座八角形大厅值得看的不只是穹顶：入口的一次预先窥见、主楼梯的上升和最终抵达被连成完整序列，让建筑本身承担起帝国自我表现的任务。",
      "preciousWhy": "这座八角形大厅值得看的不只是穹顶：入口的一次预先窥见、主楼梯的上升和最终抵达被连成完整序列，让建筑本身承担起帝国自我表现的任务。"
    },
    {
      "id": "vienna-ant-01-gemma-augustea",
      "ch": "vienna-ch-02-power",
      "zh": "奥古斯都宝石",
      "en": "Gemma Augustea",
      "by": "罗马，早期帝国时期",
      "date": "公元9—12年",
      "material": "双层阿拉伯缟玛瑙；17世纪金圈与背面镂空装饰",
      "place": "第XVI厅 · 确认在展",
      "tag": "绝对不可错过",
      "significance": "稀世珍品",
      "availabilityTag": "",
      "time": "约10分钟",
      "image": "https://www.khm.at/pics/59171/ANSA_IXa_79_1_CD_web1.jpg",
      "imageSource": "https://www.khm.at/kunstwerke/gemma-augustea-59171",
      "imageCaption": "奥古斯都宝石，罗马，早期帝国时期，公元9—12年。",
      "imageKind": "work",
      "source": "https://www.khm.at/kunstwerke/gemma-augustea-59171",
      "cardSummary": "一块宫廷尺度的缟玛瑙，把奥古斯都、继承人、胜利与俘虏压进上下两层：它值得看的不只是精细雕工，而是罗马帝国怎样把战争、和平和王朝连续性编成一幅可携带的权力图像。",
      "preciousWhy": "一块宫廷尺度的缟玛瑙，把奥古斯都、继承人、胜利与俘虏压进上下两层：它值得看的不只是精细雕工，而是罗马帝国怎样把战争、和平和王朝连续性编成一幅可携带的权力图像。"
    },
    {
      "id": "vienna-ant-04-bacchanalia-decree",
      "ch": "vienna-ch-02-power",
      "zh": "元老院关于酒神祭仪的决议",
      "en": "Senatus Consultum de Bacchanalibus",
      "by": "古罗马 · 罗马共和国",
      "date": "公元前186年",
      "material": "青铜",
      "place": "主馆古物收藏；馆方标原件在展，现场须以展签辨认原件与复制件",
      "tag": "绝对不可错过",
      "significance": "稀世珍品",
      "availabilityTag": "",
      "time": "8—12分钟",
      "image": "https://www.khm.at/pics/52468/ANSA_III_168_45581_ret_web1.jpg",
      "imageSource": "https://www.khm.at/kunstwerke/senatus-consultum-de-bacchanalibus-52468",
      "imageCaption": "元老院关于酒神祭仪的决议，古罗马 · 罗马共和国，公元前186年。",
      "imageKind": "work",
      "source": "https://www.khm.at/kunstwerke/senatus-consultum-de-bacchanalibus-52468",
      "cardSummary": "一块地方公告用的青铜板，保存了罗马元老院怎样把宗教管制变成许可、宣读与公开展示的执行程序；它还是这项决议唯一存世的文本副本，也是馆方所称现存最早的拉丁文元老院决议文本。",
      "preciousWhy": "一块地方公告用的青铜板，保存了罗马元老院怎样把宗教管制变成许可、宣读与公开展示的执行程序；它还是这项决议唯一存世的文本副本，也是馆方所称现存最早的拉丁文元老院决议文本。"
    },
    {
      "id": "vienna-ant-02-nagyszentmiklos-treasure",
      "ch": "vienna-ch-02-power",
      "zh": "纳吉圣米克洛什金宝藏",
      "en": "Gold Treasure of Nagyszentmiklós",
      "by": "迁徙时期／中世纪早期，多文化归属未定",
      "date": "7—9世纪（部分器物或为8世纪）",
      "material": "金；壶、杯、碗、带扣浅盘、饮角等23件器皿",
      "place": "KHM古物收藏；馆藏轮换",
      "tag": "绝对不可错过",
      "significance": "稀世珍品",
      "availabilityTag": "馆藏轮换",
      "time": "12—15分钟",
      "image": "https://www.khm.at/pics/71220/ANSA_VIIb_33_202203_01_web1.jpg",
      "imageSource": "https://www.khm.at/kunstwerke/medaillonkrug-71220",
      "imageCaption": "纳吉圣米克洛什金宝藏，迁徙时期／中世纪早期，多文化归属未定，7—9世纪（部分器物或为8世纪）。",
      "imageKind": "work",
      "source": "https://www.khm.at/kunstwerke/medaillonkrug-71220",
      "cardSummary": "这组23件金器的分量，不只在黄金，也在器物彼此之间的关系：成对的杯与壶、不同文字和多种装饰，共同留下了一套早期中世纪精英宴饮器具的复杂档案。它与晚期阿瓦尔文化关系密切，却仍拒绝被轻易归进单一民族；馆藏轮换，参观时未必能见到全组同时陈列。",
      "preciousWhy": "这组23件金器的分量，不只在黄金，也在器物彼此之间的关系：成对的杯与壶、不同文字和多种装饰，共同留下了一套早期中世纪精英宴饮器具的复杂档案。它与晚期阿瓦尔文化关系密切，却仍拒绝被轻易归进单一民族；馆藏轮换，参观时未必能见到全组同时陈列。"
    },
    {
      "id": "vienna-kk-05-rudolf-ii-bust",
      "ch": "vienna-ch-02-power",
      "zh": "皇帝鲁道夫二世胸像",
      "en": "Emperor Rudolf II",
      "by": "阿德里安·德·弗里斯 Adriaen de Vries · 尼德兰",
      "date": "1603年",
      "material": "青铜",
      "place": "维也纳艺术史博物馆主馆艺术珍宝馆第XXVII厅 · 确认在展",
      "tag": "强烈推荐",
      "significance": "重要藏品",
      "availabilityTag": "",
      "time": "5—8分钟",
      "image": "https://www.khm.at/pics/91513/KK_5506_01_ret_web1.jpg",
      "imageSource": "https://www.khm.at/en/artworks/emperor-rudolf-ii-91513",
      "imageCaption": "皇帝鲁道夫二世胸像，阿德里安·德·弗里斯 Adriaen de Vries · 尼德兰，1603年。",
      "imageKind": "work",
      "source": "https://www.khm.at/en/artworks/emperor-rudolf-ii-91513",
      "cardSummary": "鲁道夫二世买下曾叔祖查理五世的胸像后，又让自己的新像以它为范本并与之成对：收藏由此不只是陈列祖先，也参与制造在世皇帝的王朝形象。转身、抬眼、华丽铠甲与寓意基座，让这尊有签名、有纪年的青铜像成为理解哈布斯堡宫廷肖像的一件重要藏品。",
      "preciousWhy": "鲁道夫二世买下曾叔祖查理五世的胸像后，又让自己的新像以它为范本并与之成对：收藏由此不只是陈列祖先，也参与制造在世皇帝的王朝形象。转身、抬眼、华丽铠甲与寓意基座，让这尊有签名、有纪年的青铜像成为理解哈布斯堡宫廷肖像的一件重要藏品。"
    },
    {
      "id": "vienna-coin-01-sigismund-guldiner",
      "ch": "vienna-ch-02-power",
      "zh": "西吉斯蒙德银古尔迪纳",
      "en": "Guldiner of Archduke Sigismund",
      "by": "蒂罗尔哈恩铸币厂",
      "date": "1486年",
      "material": "银，铸打",
      "place": "钱币馆第 I 室",
      "tag": "强烈推荐",
      "significance": "重要藏品",
      "availabilityTag": "",
      "time": "4—6 分钟",
      "image": "https://www.khm.at/pics/1009266/MK_001347ba_1.jpg",
      "imageSource": "https://www.khm.at/kunstwerke/ehg-sigismund-guldiner-frontal-im-harnisch-stehend-turnierreiter-1009266",
      "imageCaption": "西吉斯蒙德银古尔迪纳，蒂罗尔哈恩铸币厂，1486年。",
      "imageKind": "work",
      "source": "https://www.khm.at/kunstwerke/ehg-sigismund-guldiner-frontal-im-harnisch-stehend-turnierreiter-1009266",
      "cardSummary": "这枚银币把金币的价值装进白银，也把统治者、权力器物与领地标志装进扩大的币面；它值得点开，因为货币改革与权力传播在这里成了同一件东西。",
      "preciousWhy": "这枚银币把金币的价值装进白银，也把统治者、权力器物与领地标志装进扩大的币面；它值得点开，因为货币改革与权力传播在这里成了同一件东西。"
    },
    {
      "id": "vienna-coin-02-charles-v-dedication-medal",
      "ch": "vienna-ch-02-power",
      "zh": "纽伦堡献给查理五世的纪念章",
      "en": "Dedication Medal of the City of Nuremberg for Charles V",
      "by": "阿尔布雷希特·丢勒 Albrecht Dürer · 纽伦堡（设计）",
      "date": "约1521年",
      "material": "银质献礼纪念章",
      "place": "维也纳艺术史博物馆钱币馆第 I 室 · 馆方确认在展",
      "tag": "强烈推荐",
      "significance": "重要藏品",
      "availabilityTag": "",
      "time": "5分钟",
      "image": "https://www.khm.at/pics/1008262/MK_000018bb_1.jpg",
      "imageSource": "https://www.khm.at/kunstwerke/medaille-1008262",
      "imageCaption": "纽伦堡献给查理五世的纪念章，阿尔布雷希特·丢勒 Albrecht Dürer · 纽伦堡（设计），约1521年。",
      "imageKind": "work",
      "source": "https://www.khm.at/kunstwerke/medaille-1008262",
      "cardSummary": "这枚银章不是流通货币，而是纽伦堡为查理五世筹划的城市献礼：丢勒等人设计、工匠制作、官员校核，连原定典礼也因瘟疫改址而落空。它值得看的，正是一项政治计划怎样被压进一枚纪念章里；馆方目前确认其在钱币馆第 I 室展出。",
      "preciousWhy": "这枚银章不是流通货币，而是纽伦堡为查理五世筹划的城市献礼：丢勒等人设计、工匠制作、官员校核，连原定典礼也因瘟疫改址而落空。它值得看的，正是一项政治计划怎样被压进一枚纪念章里；馆方目前确认其在钱币馆第 I 室展出。"
    },
    {
      "id": "vienna-egy-01-ka-ni-nisut-chapel",
      "ch": "vienna-ch-03-afterlife-story",
      "zh": "卡尼尼苏特祭祀室",
      "en": "Chapel of Ka-ni-nisut",
      "by": "古埃及，吉萨",
      "date": "第五王朝早期，约公元前2500年",
      "material": "彩绘石灰岩祭祀室",
      "place": "维也纳艺术史博物馆埃及与近东收藏，第II厅",
      "tag": "强烈推荐",
      "significance": "重要藏品",
      "availabilityTag": "",
      "time": "8—12分钟",
      "image": "https://www.khm.at/pics/317061/AEOS_8006_35392_web1.jpg",
      "imageSource": "https://www.khm.at/en/artworks/chapel-of-ka-ni-nisut-317061",
      "imageCaption": "卡尼尼苏特祭祀室，古埃及，吉萨，第五王朝早期，约公元前2500年。",
      "imageKind": "work",
      "source": "https://www.khm.at/en/artworks/chapel-of-ka-ni-nisut-317061",
      "cardSummary": "这不是从墓里搬来的一组零散浮雕，而是一间可以走入的古王国祭祀空间。墓主人、家属、书吏、宰牲与运送供品的场景围绕假门展开，让人看见约四千五百年前，来世信仰怎样被落实为一套由活人反复执行的礼仪。",
      "preciousWhy": "这不是从墓里搬来的一组零散浮雕，而是一间可以走入的古王国祭祀空间。墓主人、家属、书吏、宰牲与运送供品的场景围绕假门展开，让人看见约四千五百年前，来世信仰怎样被落实为一套由活人反复执行的礼仪。"
    },
    {
      "id": "vienna-egy-02-reserve-head",
      "ch": "vienna-ch-03-afterlife-story",
      "zh": "储备头像",
      "en": "Reserve Head",
      "by": "古埃及，吉萨",
      "date": "第四王朝胡夫统治期，约公元前 2609–2584 年",
      "material": "石灰岩",
      "place": "埃及与近东收藏第 VII 厅；确认在展（2026-07-24 核验）",
      "tag": "强烈推荐",
      "significance": "重要藏品",
      "availabilityTag": "",
      "time": "5 分钟",
      "image": "https://www.khm.at/pics/322358/AEOS_7787_01_web1.jpg",
      "imageSource": "https://www.khm.at/en/artworks/reserve-head-322358",
      "imageCaption": "储备头像，古埃及，吉萨，第四王朝胡夫统治期，约公元前 2609–2584 年。",
      "imageKind": "work",
      "source": "https://www.khm.at/en/artworks/reserve-head-322358",
      "cardSummary": "这颗为墓葬地下空间制作的独立石灰岩头像，把精细面孔、未知身份与可能有意造成的损伤留在一起；它最值得看的，正是古埃及人为何需要这种头像至今仍没有确定答案。",
      "preciousWhy": "这颗为墓葬地下空间制作的独立石灰岩头像，把精细面孔、未知身份与可能有意造成的损伤留在一起；它最值得看的，正是古埃及人为何需要这种头像至今仍没有确定答案。"
    },
    {
      "id": "vienna-egy-04-kai-pu-ptah-ipep",
      "ch": "vienna-ch-03-afterlife-story",
      "zh": "凯普普塔与伊佩普双人像",
      "en": "Statue Group of Kai-pu-ptah and Ipep",
      "by": "古埃及，吉萨",
      "date": "第五王朝晚期，约公元前 2400 年",
      "material": "彩绘石灰岩",
      "place": "埃及与近东收藏第 VII 厅 · 确认在展",
      "tag": "强烈推荐",
      "significance": "特色看点",
      "availabilityTag": "",
      "time": "4 分钟",
      "image": "https://www.khm.at/pics/323871/AEOS_7444_89_web1.jpg",
      "imageSource": "https://www.khm.at/en/artworks/statue-group-of-kai-pu-ptah-and-ipep-323871",
      "imageCaption": "凯普普塔与伊佩普双人像，古埃及，吉萨，第五王朝晚期，约公元前 2400 年。",
      "imageKind": "work",
      "source": "https://www.khm.at/en/artworks/statue-group-of-kai-pu-ptah-and-ipep-323871",
      "cardSummary": "两个人的姓名写在底座上，彼此关系却仍未被可靠材料说明。这组古王国墓葬双人像最值得看的，是它怎样同时展示身份记录的清楚与解释的限度。",
      "preciousWhy": "两个人的姓名写在底座上，彼此关系却仍未被可靠材料说明。这组古王国墓葬双人像最值得看的，是它怎样同时展示身份记录的清楚与解释的限度。"
    },
    {
      "id": "vienna-egy-05-gem-nef-hor-bak",
      "ch": "vienna-ch-03-afterlife-story",
      "zh": "杰姆内夫霍尔巴克抱龛跪像",
      "en": "Naophorous Statue of Gem-nef-hor-bak",
      "by": "古埃及，可能来自塞易斯",
      "date": "第三十王朝，公元前4世纪上半叶",
      "material": "花岗闪长岩",
      "place": "埃及与近东收藏第 IX 厅 · 确认在展",
      "tag": "时间充裕再看",
      "significance": "特色看点",
      "availabilityTag": "",
      "time": "4—6分钟",
      "image": "https://www.khm.at/pics/316886/AE_INV_62_08.jpg",
      "imageSource": "https://www.khm.at/en/artworks/naophorous-statue-of-gem-nef-hor-bak-316886",
      "imageCaption": "杰姆内夫霍尔巴克抱龛跪像，古埃及，可能来自塞易斯，第三十王朝，公元前4世纪上半叶。",
      "imageKind": "work",
      "source": "https://www.khm.at/en/artworks/naophorous-statue-of-gem-nef-hor-bak-316886",
      "cardSummary": "一个人怎样让自己的礼敬在神庙里持续出现？这尊跪像把杰姆内夫霍尔巴克、他怀抱的神龛、龛中的奈特女神和两组铭文合为一个宗教对象；约1560年的君士坦丁堡购藏经历，又让它成为维也纳埃及收藏最早期的见证之一。",
      "preciousWhy": "一个人怎样让自己的礼敬在神庙里持续出现？这尊跪像把杰姆内夫霍尔巴克、他怀抱的神龛、龛中的奈特女神和两组铭文合为一个宗教对象；约1560年的君士坦丁堡购藏经历，又让它成为维也纳埃及收藏最早期的见证之一。"
    },
    {
      "id": "vienna-egy-03-babylon-lion",
      "ch": "vienna-ch-03-afterlife-story",
      "zh": "巴比伦行进狮子砖墙浮雕",
      "en": "Wall Section with Relief of a Striding Lion",
      "by": "新巴比伦，巴比伦游行大道",
      "date": "尼布甲尼撒二世时期，公元前 604–562 年",
      "material": "陶土、彩色釉砖",
      "place": "埃及与近东收藏第 VIa 厅 · 确认在展",
      "tag": "强烈推荐",
      "significance": "重要藏品",
      "availabilityTag": "",
      "time": "5–8 分钟",
      "image": "https://www.khm.at/pics/376850/AEOS_SEM_951_ret_web1.jpg",
      "imageSource": "https://www.khm.at/kunstwerke/wandstueck-mit-dem-relief-eines-schreitenden-loewen-376850",
      "imageCaption": "巴比伦行进狮子砖墙浮雕，新巴比伦，巴比伦游行大道，尼布甲尼撒二世时期，公元前 604–562 年。",
      "imageKind": "work",
      "source": "https://www.khm.at/kunstwerke/wandstueck-mit-dem-relief-eines-schreitenden-loewen-376850",
      "cardSummary": "一只迈步的釉砖狮子，原本是巴比伦游行大道两侧反复出现的墙面构件：从这一段残存建筑中，可以看懂宗教象征怎样被编入城市入口。",
      "preciousWhy": "一只迈步的釉砖狮子，原本是巴比伦游行大道两侧反复出现的墙面构件：从这一段残存建筑中，可以看懂宗教象征怎样被编入城市入口。"
    },
    {
      "id": "vienna-ant-03-brygos-skyphos",
      "ch": "vienna-ch-03-afterlife-story",
      "zh": "布里戈斯大杯：普里阿摩斯赎回赫克托耳遗体",
      "en": "Brygos Skyphos: The Ransom of Hector",
      "by": "布里戈斯陶工坊／布里戈斯画家 · 古希腊",
      "date": "约公元前490年",
      "material": "陶土，阿提卡红绘",
      "place": "Kunsthistorisches Museum Vienna 古物馆第XIV厅（核验于2026-07-24）",
      "tag": "强烈推荐",
      "significance": "重要藏品",
      "availabilityTag": "",
      "time": "6—8分钟",
      "image": "https://www.khm.at/pics/56696/ANSA_IV_3710_3672_fin_web1.jpg",
      "imageSource": "https://www.khm.at/kunstwerke/hektors-loesung-56696",
      "imageCaption": "布里戈斯大杯：普里阿摩斯赎回赫克托耳遗体，布里戈斯陶工坊／布里戈斯画家 · 古希腊，约公元前490年。",
      "imageKind": "work",
      "source": "https://www.khm.at/kunstwerke/hektors-loesung-56696",
      "cardSummary": "这只大杯把《伊利亚特》的英雄战争压进一次安静而艰难的请求：老王普里阿摩斯走向杀子者阿喀琉斯，赫克托耳的遗体就横在宴饮床下。克制的人物安排与约12升的惊人容量，让故事、器形和原始用途一起值得细看。",
      "preciousWhy": "这只大杯把《伊利亚特》的英雄战争压进一次安静而艰难的请求：老王普里阿摩斯走向杀子者阿喀琉斯，赫克托耳的遗体就横在宴饮床下。克制的人物安排与约12升的惊人容量，让故事、器形和原始用途一起值得细看。"
    },
    {
      "id": "vienna-ant-05-amazon-sarcophagus",
      "ch": "vienna-ch-03-afterlife-story",
      "zh": "亚马孙之战石棺",
      "en": "Sarcophagus with Fighting Amazons",
      "by": "希腊文化",
      "date": "公元前4世纪后半叶",
      "material": "彭特利库斯大理石",
      "place": "古物馆第XI厅在展",
      "tag": "强烈推荐",
      "significance": "重要藏品",
      "availabilityTag": "",
      "time": "8—10分钟",
      "image": "https://www.khm.at/pics/50832/ANSA_I_169_03_web1.jpg",
      "imageSource": "https://www.khm.at/kunstwerke/amazonensarkophag-50832",
      "imageCaption": "亚马孙之战石棺，希腊文化，公元前4世纪后半叶。",
      "imageKind": "work",
      "source": "https://www.khm.at/kunstwerke/amazonensarkophag-50832",
      "cardSummary": "从塞浦路斯王城出土的这具石棺，把墓葬、进口大理石和环绕四面的神话战争连在一起。它值得细看，因为希腊人与亚马孙的服装、武器和骑战场面，不只讲一场传奇，也展示当地精英如何借泛希腊视觉语言塑造纪念。",
      "preciousWhy": "从塞浦路斯王城出土的这具石棺，把墓葬、进口大理石和环绕四面的神话战争连在一起。它值得细看，因为希腊人与亚马孙的服装、武器和骑战场面，不只讲一场传奇，也展示当地精英如何借泛希腊视觉语言塑造纪念。"
    },
    {
      "id": "vienna-ant-06-theseus-mosaic",
      "ch": "vienna-ch-03-afterlife-story",
      "zh": "忒修斯马赛克",
      "en": "Theseus Mosaic",
      "by": "古罗马，发现于萨尔茨堡附近别墅",
      "date": "公元4世纪",
      "material": "大理石与石灰石小块",
      "place": "主馆古物馆第XI厅在展，嵌入展厅地面",
      "tag": "强烈推荐",
      "significance": "特色看点",
      "availabilityTag": "",
      "time": "6—8分钟",
      "image": "https://www.khm.at/pics/52079/Ansa_II_20_Gesamt_web1.jpg",
      "imageSource": "https://www.khm.at/en/artworks/theseusmosaik-52079",
      "imageCaption": "忒修斯马赛克，古罗马，发现于萨尔茨堡附近别墅，公元4世纪。",
      "imageKind": "work",
      "source": "https://www.khm.at/en/artworks/theseusmosaik-52079",
      "cardSummary": "中央是忒修斯杀死米诺陶洛斯，周围却把阿里阿德涅交线、乘船离开和她后来的命运都保留下来。这块马赛克值得看的，不只是一场英雄胜利，还有一段被铺进罗马别墅、又嵌入维也纳博物馆地面的完整神话。",
      "preciousWhy": "中央是忒修斯杀死米诺陶洛斯，周围却把阿里阿德涅交线、乘船离开和她后来的命运都保留下来。这块马赛克值得看的，不只是一场英雄胜利，还有一段被铺进罗马别墅、又嵌入维也纳博物馆地面的完整神话。"
    },
    {
      "id": "vienna-kk-01-saliera",
      "ch": "vienna-ch-04-kunstkammer",
      "zh": "盐罐",
      "en": "Saliera",
      "by": "本韦努托·切利尼 Benvenuto Cellini · 佛罗伦萨",
      "date": "1540–1543",
      "material": "黄金、珐琅、乌木、象牙",
      "place": "Kunsthistorisches Museum 艺术珍宝馆 XXIX 厅 · 确认在展",
      "tag": "绝对不可错过",
      "significance": "稀世珍品",
      "availabilityTag": "",
      "time": "8–12 分钟",
      "image": "https://www.khm.at/pics/87080/KK_881_012006_14.jpg",
      "imageSource": "https://www.khm.at/en/artworks/saliera-87080",
      "imageCaption": "盐罐，本韦努托·切利尼 Benvenuto Cellini · 佛罗伦萨，1540–1543。",
      "imageKind": "work",
      "source": "https://www.khm.at/en/artworks/saliera-87080",
      "cardSummary": "一只盐罐为什么要装下海、陆、四风和一天时段？切利尼把调味品的来源、法国国王的徽记与黄金金工合成一套桌上宇宙；更难替代的是，据馆方资料，这是他唯一存世的金质作品。",
      "preciousWhy": "一只盐罐为什么要装下海、陆、四风和一天时段？切利尼把调味品的来源、法国国王的徽记与黄金金工合成一套桌上宇宙；更难替代的是，据馆方资料，这是他唯一存世的金质作品。"
    },
    {
      "id": "vienna-kk-07-rock-crystal-pyramid",
      "ch": "vienna-ch-04-kunstkammer",
      "zh": "水晶金字塔",
      "en": "Rock Crystal Pyramid",
      "by": "迪奥尼西奥·米塞罗尼 Dionysio Miseroni · 布拉格",
      "date": "1653年",
      "material": "水晶、鎏金银与珐琅装配",
      "place": "维也纳艺术史博物馆艺术珍宝馆第XXII厅 · 确认在展",
      "tag": "绝对不可错过",
      "significance": "稀世珍品",
      "availabilityTag": "",
      "time": "8—10分钟",
      "image": "https://www.khm.at/pics/580539/KK_2251_44312.jpg",
      "imageSource": "https://www.khm.at/en/artworks/bergkristall-pyramide-580539",
      "imageCaption": "水晶金字塔，迪奥尼西奥·米塞罗尼 Dionysio Miseroni · 布拉格，1653年。",
      "imageKind": "work",
      "source": "https://www.khm.at/en/artworks/bergkristall-pyramide-580539",
      "cardSummary": "四层看似分别制作的水晶杯筒，其实依次取自同一块大型水晶：上一步若失手，下一层便无从补救。这件高达145.4厘米、带有皇帝铭文和作者签名纪年的宫廷奇珍，把昂贵材料变成了一份肉眼可读的工艺规划。",
      "preciousWhy": "四层看似分别制作的水晶杯筒，其实依次取自同一块大型水晶：上一步若失手，下一层便无从补救。这件高达145.4厘米、带有皇帝铭文和作者签名纪年的宫廷奇珍，把昂贵材料变成了一份肉眼可读的工艺规划。"
    },
    {
      "id": "vienna-kk-08-bellerophon-pegasus",
      "ch": "vienna-ch-04-kunstkammer",
      "zh": "柏勒洛丰驯服珀伽索斯",
      "en": "Bellerophon Taming Pegasus",
      "by": "贝尔托尔多·迪·乔瓦尼 Bertoldo di Giovanni · 意大利（模型）；阿德里亚诺·菲奥伦蒂诺 Adriano Fiorentino · 意大利（铸造）",
      "date": "约1481/1482年",
      "material": "青铜",
      "place": "维也纳艺术史博物馆 Kunstkammer，第XXXIV厅在展",
      "tag": "绝对不可错过",
      "significance": "稀世珍品",
      "availabilityTag": "",
      "time": "6—8分钟",
      "image": "https://www.khm.at/pics/91603/KK_5596_01_web1.jpg",
      "imageSource": "https://www.khm.at/en/artworks/bellerophon-taming-pegasus-91603",
      "imageCaption": "柏勒洛丰驯服珀伽索斯，贝尔托尔多·迪·乔瓦尼 Bertoldo di Giovanni · 意大利（模型）；阿德里亚诺·菲奥伦蒂诺 Adriano Fiorentino · 意大利（铸造），约1481/1482年。",
      "imageKind": "work",
      "source": "https://www.khm.at/en/artworks/bellerophon-taming-pegasus-91603",
      "cardSummary": "这件早期文艺复兴青铜把古典文本里较温和的驯马，改造成英雄与有翼马的激烈角力。它不仅是古代以后这一题材的首次重现，还让雕像亲口报出“谁塑造我、谁铸造我”，把一座作品背后的两种手艺也留了下来。",
      "preciousWhy": "这件早期文艺复兴青铜把古典文本里较温和的驯马，改造成英雄与有翼马的激烈角力。它不仅是古代以后这一题材的首次重现，还让雕像亲口报出“谁塑造我、谁铸造我”，把一座作品背后的两种手艺也留了下来。"
    },
    {
      "id": "vienna-kk-03-automaton-ship",
      "ch": "vienna-ch-04-kunstkammer",
      "zh": "船形自动机械",
      "en": "Automaton in the Form of a Ship",
      "by": "汉斯·施洛特海姆 Hans Schlottheim · 奥格斯堡",
      "date": "1585年",
      "material": "鎏金并局部彩绘的银、铜合金、铁",
      "place": "Kunsthistorisches Museum 艺术珍宝馆 XXVII 厅 · 确认在展",
      "tag": "强烈推荐",
      "significance": "重要藏品",
      "availabilityTag": "",
      "time": "5—7 分钟",
      "image": "https://www.khm.at/pics/87073/KK_874_2012_04_web1.jpg",
      "imageSource": "https://www.khm.at/en/artworks/automaton-in-the-form-of-a-ship-87073",
      "imageCaption": "船形自动机械，汉斯·施洛特海姆 Hans Schlottheim · 奥格斯堡，1585年。",
      "imageKind": "work",
      "source": "https://www.khm.at/en/artworks/automaton-in-the-form-of-a-ship-87073",
      "cardSummary": "它把宫廷宴桌变成一座会移动、奏乐、驱动人物并鸣炮的微型权力舞台；真正值得看的，是精密机械怎样与人物、纹章和帝国宣言合成一次完整表演。",
      "preciousWhy": "它把宫廷宴桌变成一座会移动、奏乐、驱动人物并鸣炮的微型权力舞台；真正值得看的，是精密机械怎样与人物、纹章和帝国宣言合成一次完整表演。"
    },
    {
      "id": "vienna-kk-04-cittern-player",
      "ch": "vienna-ch-04-kunstkammer",
      "zh": "西特琴演奏者自动机械",
      "en": "Automaton, so-called Cittern Player",
      "by": "作者不详；西班牙（？）",
      "date": "16 世纪后半叶",
      "material": "彩绘木、铁、亚麻、丝锦",
      "place": "Kunsthistorisches Museum 艺术珍宝馆 XXXII 厅",
      "tag": "强烈推荐",
      "significance": "重要藏品",
      "availabilityTag": "",
      "time": "5 分钟",
      "image": "https://www.khm.at/pics/96017/KK_10000_10638_web1.jpg",
      "imageSource": "https://www.khm.at/en/artworks/automaton-so-called-cittern-player-96017",
      "imageCaption": "西特琴演奏者自动机械，作者不详；西班牙（？），16 世纪后半叶。",
      "imageKind": "work",
      "source": "https://www.khm.at/en/artworks/automaton-so-called-cittern-player-96017",
      "cardSummary": "一件 44 厘米高的宫廷女性形自动机械，把铁制机构藏进织物衣裙和木制身体，再以拨琴、转头与碎步模拟生命。它曾被归于名匠 Juanelo Turriano，但作者至今未定；真正值得看的，是 16 世纪宫廷如何把“技术模仿自然”做成眼前的一场表演。",
      "preciousWhy": "一件 44 厘米高的宫廷女性形自动机械，把铁制机构藏进织物衣裙和木制身体，再以拨琴、转头与碎步模拟生命。它曾被归于名匠 Juanelo Turriano，但作者至今未定；真正值得看的，是 16 世纪宫廷如何把“技术模仿自然”做成眼前的一场表演。"
    },
    {
      "id": "vienna-kk-06-dragon-bowl",
      "ch": "vienna-ch-04-kunstkammer",
      "zh": "贝壳形碗（龙碗）",
      "en": "Shell-shaped Bowl, so-called Dragon Bowl",
      "by": "加斯帕罗·米塞罗尼 Gasparo Miseroni · 米兰",
      "date": "约1565/1570年",
      "material": "青金石、金、珐琅、红宝石、祖母绿、珍珠、石榴石",
      "place": "Kunsthistorisches Museum Vienna，艺术珍宝馆第XXVIII厅",
      "tag": "强烈推荐",
      "significance": "重要藏品",
      "availabilityTag": "",
      "time": "5—8分钟",
      "image": "https://www.khm.at/pics/87856/KK_1851_Neu_16_web1.jpg",
      "imageSource": "https://www.khm.at/en/artworks/shell-shaped-bowl-so-called-dragon-bowl-87856",
      "imageCaption": "贝壳形碗（龙碗），加斯帕罗·米塞罗尼 Gasparo Miseroni · 米兰，约1565/1570年。",
      "imageKind": "work",
      "source": "https://www.khm.at/en/artworks/shell-shaped-bowl-so-called-dragon-bowl-87856",
      "cardSummary": "一块青金石并没有被金工遮成豪华底座：它的贝壳轮廓和天然石纹直接参与塑造龙身。石匠与金匠从设计之初便须彼此配合，这只小碗因此浓缩了文艺复兴宫廷珍宝馆最看重的较量——稀贵材料能被人的手艺组织到什么程度。",
      "preciousWhy": "一块青金石并没有被金工遮成豪华底座：它的贝壳轮廓和天然石纹直接参与塑造龙身。石匠与金匠从设计之初便须彼此配合，这只小碗因此浓缩了文艺复兴宫廷珍宝馆最看重的较量——稀贵材料能被人的手艺组织到什么程度。"
    },
    {
      "id": "vienna-kk-02-krumau-madonna",
      "ch": "vienna-ch-04-kunstkammer",
      "zh": "克鲁姆洛夫圣母",
      "en": "Virgin and Child, so-called Krumau Madonna",
      "by": "匿名 · 约 1400 年布拉格宫廷艺术圈（可能）",
      "date": "约 1390/1400",
      "material": "石灰质砂岩，残存彩绘与镀金",
      "place": "Kunsthistorisches Museum 艺术珍宝馆 XXXVI 厅 · 确认在展",
      "tag": "强烈推荐",
      "significance": "重要藏品",
      "availabilityTag": "",
      "time": "6—8 分钟",
      "image": "https://www.khm.at/pics/96174/KK_10156_02_web1.jpg",
      "imageSource": "https://www.khm.at/en/artworks/virgin-and-child-so-called-krumau-madonna-96174",
      "imageCaption": "克鲁姆洛夫圣母，匿名 · 约 1400 年布拉格宫廷艺术圈（可能），约 1390/1400。",
      "imageKind": "work",
      "source": "https://www.khm.at/en/artworks/virgin-and-child-so-called-krumau-madonna-96174",
      "cardSummary": "弯曲的站姿、翻涌的厚衣褶和扭转的婴儿身体，让这件约 1400 年的名作同时拥有天后的华丽与母子的亲近；表面残留的彩绘和镀金，还保留着它昔日彩色外观的一点线索。",
      "preciousWhy": "弯曲的站姿、翻涌的厚衣褶和扭转的婴儿身体，让这件约 1400 年的名作同时拥有天后的华丽与母子的亲近；表面残留的彩绘和镀金，还保留着它昔日彩色外观的一点线索。"
    },
    {
      "id": "vienna-pg-01-tower-of-babel",
      "ch": "vienna-ch-05-bruegel",
      "zh": "巴别塔",
      "en": "The Tower of Babel",
      "by": "老彼得·勃鲁盖尔 Pieter Bruegel the Elder · 尼德兰",
      "date": "1563",
      "material": "橡木板绘画",
      "place": "Kunsthistorisches Museum Vienna，Gemäldegalerie Room X（确认在展）",
      "tag": "绝对不可错过",
      "significance": "稀世珍品",
      "availabilityTag": "",
      "time": "8—12 分钟",
      "image": "https://www.khm.at/pics/323/GG_1026_2018_CD_web1.jpg",
      "imageSource": "https://www.khm.at/en/object/323/",
      "imageCaption": "巴别塔，老彼得·勃鲁盖尔 Pieter Bruegel the Elder · 尼德兰，1563。",
      "imageKind": "work",
      "source": "https://www.khm.at/en/object/323/",
      "cardSummary": "一则关于语言与分散的圣经故事，被勃鲁盖尔铺成一座仍在运转的庞大港城工地。它值得停留，不只因为巨塔有名，更因为这件明确纪年的经典版本把城市、船只与繁复施工压进同一幅画，让宏大的集体目标显出具体而复杂的建造过程。",
      "preciousWhy": "一则关于语言与分散的圣经故事，被勃鲁盖尔铺成一座仍在运转的庞大港城工地。它值得停留，不只因为巨塔有名，更因为这件明确纪年的经典版本把城市、船只与繁复施工压进同一幅画，让宏大的集体目标显出具体而复杂的建造过程。"
    },
    {
      "id": "vienna-pg-02-hunters-in-the-snow",
      "ch": "vienna-ch-05-bruegel",
      "zh": "雪中猎人（冬）",
      "en": "Hunters in the Snow (Winter)",
      "by": "老彼得·勃鲁盖尔 Pieter Bruegel the Elder · 尼德兰",
      "date": "1565",
      "material": "橡木板",
      "place": "Kunsthistorisches Museum Vienna，Gemäldegalerie Room X",
      "tag": "绝对不可错过",
      "significance": "稀世珍品",
      "availabilityTag": "",
      "time": "8—10 分钟",
      "image": "https://www.khm.at/pics/327/GG_1838_2018_CD_web1.jpg",
      "imageSource": "https://www.khm.at/en/artworks/hunters-in-the-snow-winter-327",
      "imageCaption": "雪中猎人（冬），老彼得·勃鲁盖尔 Pieter Bruegel the Elder · 尼德兰，1565。",
      "imageKind": "work",
      "source": "https://www.khm.at/en/artworks/hunters-in-the-snow-winter-327",
      "cardSummary": "勃鲁盖尔把冬天从一个月令人物扩展为整片风景的共同状态：低产归猎、冰上游戏与覆雪山谷同时成立，也让这幅画成为存世六季组画中无法替代的冬季一章。",
      "preciousWhy": "勃鲁盖尔把冬天从一个月令人物扩展为整片风景的共同状态：低产归猎、冰上游戏与覆雪山谷同时成立，也让这幅画成为存世六季组画中无法替代的冬季一章。"
    },
    {
      "id": "vienna-pg-03-childrens-games",
      "ch": "vienna-ch-05-bruegel",
      "zh": "儿童游戏",
      "en": "Children's Games",
      "by": "老彼得·勃鲁盖尔 Pieter Bruegel the Elder · 尼德兰",
      "date": "1560",
      "material": "橡木板",
      "place": "KHM 绘画馆 Room X · 确认在展（2026-07-24 核验）",
      "tag": "绝对不可错过",
      "significance": "重要藏品",
      "availabilityTag": "",
      "time": "8—12 分钟",
      "image": "https://www.khm.at/pics/321/GG_1017_XXL.jpg",
      "imageSource": "https://www.khm.at/en/artworks/children-s-games-321",
      "imageCaption": "儿童游戏，老彼得·勃鲁盖尔 Pieter Bruegel the Elder · 尼德兰，1560。",
      "imageKind": "work",
      "source": "https://www.khm.at/en/artworks/children-s-games-321",
      "cardSummary": "超过 230 名儿童和 83 种游戏被放进同一片城市空间，却没有一个主角替你统领全局。勃鲁盖尔用高视点保住每个小群的可读性，也让这幅“游戏百科全书”只能慢慢展开：它既保存十六世纪的日常玩耍，也把观看本身变成一次不断选择路线的游戏。",
      "preciousWhy": "超过 230 名儿童和 83 种游戏被放进同一片城市空间，却没有一个主角替你统领全局。勃鲁盖尔用高视点保住每个小群的可读性，也让这幅“游戏百科全书”只能慢慢展开：它既保存十六世纪的日常玩耍，也把观看本身变成一次不断选择路线的游戏。"
    },
    {
      "id": "vienna-pg-04-peasant-wedding",
      "ch": "vienna-ch-05-bruegel",
      "zh": "农民婚礼",
      "en": "Peasant Wedding",
      "by": "老彼得·勃鲁盖尔 Pieter Bruegel the Elder · 尼德兰",
      "date": "1568",
      "material": "橡木板",
      "place": "画廊 X 室 · 确认在展",
      "tag": "绝对不可错过",
      "significance": "重要藏品",
      "availabilityTag": "",
      "time": "6—8 分钟",
      "image": "https://www.khm.at/pics/330/GG_1027_Web.jpg",
      "imageSource": "https://www.khm.at/en/artworks/peasant-wedding-330",
      "imageCaption": "农民婚礼，老彼得·勃鲁盖尔 Pieter Bruegel the Elder · 尼德兰，1568。",
      "imageKind": "work",
      "source": "https://www.khm.at/en/artworks/peasant-wedding-330",
      "cardSummary": "勃鲁盖尔把乡村婚宴的吃饭、上菜和身份差异推到画面中心；最值得点开的，是那块临时充当托盘的门板，怎样把真实生活的局促与一幅严密构成的大画连在一起。",
      "preciousWhy": "勃鲁盖尔把乡村婚宴的吃饭、上菜和身份差异推到画面中心；最值得点开的，是那块临时充当托盘的门板，怎样把真实生活的局促与一幅严密构成的大画连在一起。"
    },
    {
      "id": "vienna-pg-05-carnival-and-lent",
      "ch": "vienna-ch-05-bruegel",
      "zh": "狂欢节与四旬斋之战",
      "en": "The Fight between Carnival and Lent",
      "by": "老彼得·勃鲁盖尔 Pieter Bruegel the Elder · 尼德兰",
      "date": "1559年",
      "material": "橡木板",
      "place": "绘画馆 Room X · 确认在展",
      "tag": "强烈推荐",
      "significance": "重要藏品",
      "availabilityTag": "",
      "time": "8—12 分钟",
      "image": "https://www.khm.at/pics/320/GG_1016_2018_CD_web1.jpg",
      "imageSource": "https://www.khm.at/en/artworks/the-fight-between-carnival-and-lent-320",
      "imageCaption": "狂欢节与四旬斋之战，老彼得·勃鲁盖尔 Pieter Bruegel the Elder · 尼德兰，1559年。",
      "imageKind": "work",
      "source": "https://www.khm.at/en/artworks/the-fight-between-carnival-and-lent-320",
      "cardSummary": "勃鲁盖尔把禁食前的酒肉狂欢与四旬斋的鱼食、礼拜和施舍压进同一座城：前景是一场用酒桶、串肉和鱼开打的滑稽比武，周围却铺开了两套完整的节期生活。这不是某一天的街头快照，而是一幅能逐处读下去的城市社会模型。",
      "preciousWhy": "勃鲁盖尔把禁食前的酒肉狂欢与四旬斋的鱼食、礼拜和施舍压进同一座城：前景是一场用酒桶、串肉和鱼开打的滑稽比武，周围却铺开了两套完整的节期生活。这不是某一天的街头快照，而是一幅能逐处读下去的城市社会模型。"
    },
    {
      "id": "vienna-pg-06-art-of-painting",
      "ch": "vienna-ch-06-painting",
      "zh": "绘画的艺术",
      "en": "The Art of Painting",
      "by": "约翰内斯·维米尔 Johannes Vermeer · 荷兰",
      "date": "约 1666/68",
      "material": "布面绘画",
      "place": "Kunsthistorisches Museum Vienna，Gemäldegalerie Room XII · 确认在展",
      "tag": "绝对不可错过",
      "significance": "稀世珍品",
      "availabilityTag": "",
      "time": "8—12 分钟",
      "image": "https://www.khm.at/pics/2574/GG_9128_CD_web1.jpg",
      "imageSource": "https://www.khm.at/en/artworks/the-art-of-painting-2574",
      "imageCaption": "绘画的艺术，约翰内斯·维米尔 Johannes Vermeer · 荷兰，约 1666/68。",
      "imageKind": "work",
      "source": "https://www.khm.at/en/artworks/the-art-of-painting-2574",
      "cardSummary": "维米尔把画家、历史缪斯和旧尼德兰地图放进同一间画室，让一幅“画家正在画画”的室内景象变成对绘画本身的追问：眼前的人物怎样被画成历史，画家的工作又怎样获得名声。帘幕后的创作过程与同作者更直接的宗教寓意画都无法彼此替代，这正是它在维米尔约三十六幅已知作品中的特殊分量。",
      "preciousWhy": "维米尔把画家、历史缪斯和旧尼德兰地图放进同一间画室，让一幅“画家正在画画”的室内景象变成对绘画本身的追问：眼前的人物怎样被画成历史，画家的工作又怎样获得名声。帘幕后的创作过程与同作者更直接的宗教寓意画都无法彼此替代，这正是它在维米尔约三十六幅已知作品中的特殊分量。"
    },
    {
      "id": "vienna-pg-07-infanta-margarita-blue",
      "ch": "vienna-ch-06-painting",
      "zh": "身着蓝裙的玛格丽特公主",
      "en": "Infanta Margarita in a Blue Dress",
      "by": "迭戈·委拉斯开兹 Diego Velázquez · 西班牙",
      "date": "1659年",
      "material": "布面绘画",
      "place": "维也纳艺术史博物馆绘画陈列馆，第10展厅；确认在展",
      "tag": "强烈推荐",
      "significance": "重要藏品",
      "availabilityTag": "",
      "time": "5—8分钟",
      "image": "https://www.khm.at/pics/2027/GG_2130_201309_CD_web1.jpg",
      "imageSource": "https://www.khm.at/en/artworks/infanta-margarita-in-a-blue-dress-2027",
      "imageCaption": "身着蓝裙的玛格丽特公主，迭戈·委拉斯开兹 Diego Velázquez · 西班牙，1659年。",
      "imageKind": "work",
      "source": "https://www.khm.at/en/artworks/infanta-margarita-in-a-blue-dress-2027",
      "cardSummary": "一幅送往维也纳、服务于王室婚姻关系的公主肖像，也是一场关于观看距离的绘画实验：近看是松散闪烁的色点，退开后才成为庄重而有体积的蓝银礼服。它还处在委拉斯开兹创作生涯的最后阶段。",
      "preciousWhy": "一幅送往维也纳、服务于王室婚姻关系的公主肖像，也是一场关于观看距离的绘画实验：近看是松散闪烁的色点，退开后才成为庄重而有体积的蓝银礼服。它还处在委拉斯开兹创作生涯的最后阶段。"
    },
    {
      "id": "vienna-pg-12-rubens-self-portrait",
      "ch": "vienna-ch-06-painting",
      "zh": "自画像",
      "en": "Self-Portrait",
      "by": "彼得·保罗·鲁本斯 Peter Paul Rubens · 弗兰德斯",
      "date": "1638/1640",
      "material": "布面绘画",
      "place": "维也纳艺术史博物馆绘画馆馆藏 · 展出状态待核验",
      "tag": "强烈推荐",
      "significance": "重要藏品",
      "availabilityTag": "展出状态待核验",
      "time": "5 分钟",
      "image": "https://www.khm.at/pics/1638/GG_527_CD_ALT_web1.jpg",
      "imageSource": "https://www.khm.at/en/artworks/self-portrait-1638",
      "imageCaption": "自画像，彼得·保罗·鲁本斯 Peter Paul Rubens · 弗兰德斯，1638/1640。",
      "imageKind": "work",
      "source": "https://www.khm.at/en/artworks/self-portrait-1638",
      "cardSummary": "鲁本斯生命最后阶段的这幅自画像，把柱、剑和手套所代表的宫廷身份，与皱纹、眼袋和松弛皮肤等年长面貌放在一起。它值得点开，不只因为画家画了自己，更因为公开地位与具体年龄同时留在了画中。绘画馆馆藏，展出状态待核验。",
      "preciousWhy": "鲁本斯生命最后阶段的这幅自画像，把柱、剑和手套所代表的宫廷身份，与皱纹、眼袋和松弛皮肤等年长面貌放在一起。它值得点开，不只因为画家画了自己，更因为公开地位与具体年龄同时留在了画中。绘画馆馆藏，展出状态待核验。"
    },
    {
      "id": "vienna-pg-13-cardinal-albergati",
      "ch": "vienna-ch-06-painting",
      "zh": "红衣主教尼科洛·阿尔贝加蒂（？）",
      "en": "Cardinal Niccolò Albergati (?)",
      "by": "扬·凡·艾克 Jan van Eyck · 早期尼德兰",
      "date": "约 1435",
      "material": "橡木板绘画",
      "place": "Kunsthistorisches Museum 绘画馆馆藏 · 展出状态未知",
      "tag": "强烈推荐",
      "significance": "重要藏品",
      "availabilityTag": "展出状态待核验",
      "time": "5—8 分钟",
      "image": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Jan%20van%20Eyck%2C%20%2C%20Kunsthistorisches%20Museum%20Wien%2C%20Gem%C3%A4ldegalerie%20-%20Kardinal%20Niccol%C3%B2%20Albergati%20%5E%20%281375-1443%29%20-%20GG%20975%20-%20Kunsthistorisches%20Museum.jpg",
      "imageSource": "https://commons.wikimedia.org/wiki/File:Jan_van_Eyck,_,_Kunsthistorisches_Museum_Wien,_Gem%C3%A4ldegalerie_-_Kardinal_Niccol%C3%B2_Albergati_%5E_(1375-1443)_-_GG_975_-_Kunsthistorisches_Museum.jpg",
      "imageCaption": "红衣主教尼科洛·阿尔贝加蒂（？），扬·凡·艾克 Jan van Eyck · 早期尼德兰，约 1435。",
      "imageKind": "work",
      "source": "https://www.khm.at/kunstwerke/kardinal-niccol-albergati-1375-1443-680",
      "cardSummary": "一张留有色彩文字注记的银尖素描，与这幅细密的油性板画保存着同一张年长面孔。两件作品放在一起，难得地让人看见凡·艾克怎样把现场记录转化为皱纹、胡茬和细小肤色变化，也说明他的关键贡献是精炼油画方法，而非“发明油画”。",
      "preciousWhy": "一张留有色彩文字注记的银尖素描，与这幅细密的油性板画保存着同一张年长面孔。两件作品放在一起，难得地让人看见凡·艾克怎样把现场记录转化为皱纹、胡茬和细小肤色变化，也说明他的关键贡献是精炼油画方法，而非“发明油画”。"
    },
    {
      "id": "vienna-pg-16-parmigianino-convex-self-portrait",
      "ch": "vienna-ch-06-painting",
      "zh": "凸面镜中的自画像",
      "en": "Self-Portrait in a Convex Mirror",
      "by": "帕尔米贾尼诺 Parmigianino · 意大利／艾米利亚",
      "date": "约 1523/1524",
      "material": "凸起的杨木板绘画",
      "place": "Kunsthistorisches Museum 绘画馆 3 室 · 确认在展",
      "tag": "强烈推荐",
      "significance": "重要藏品",
      "availabilityTag": "",
      "time": "6–8 分钟",
      "image": "https://www.khm.at/pics/1407/GG_286_CD_web1.jpg",
      "imageSource": "https://www.khm.at/en/artworks/selbstbildnis-im-konvexspiegel-1407",
      "imageCaption": "凸面镜中的自画像，帕尔米贾尼诺 Parmigianino · 意大利／艾米利亚，约 1523/1524。",
      "imageKind": "work",
      "source": "https://www.khm.at/en/artworks/selbstbildnis-im-konvexspiegel-1407",
      "cardSummary": "帕尔米贾尼诺把凸面镜中的变形画到一块真正凸起的圆形木板上：放大的手、缩远的脸和弯曲的房间既展示错觉本领，也让这幅随他赴罗马争取教皇委托的小画成为一张难忘的“能力证明”。",
      "preciousWhy": "帕尔米贾尼诺把凸面镜中的变形画到一块真正凸起的圆形木板上：放大的手、缩远的脸和弯曲的房间既展示错觉本领，也让这幅随他赴罗马争取教皇委托的小画成为一张难忘的“能力证明”。"
    },
    {
      "id": "vienna-pg-15-summer",
      "ch": "vienna-ch-06-painting",
      "zh": "夏",
      "en": "Summer",
      "by": "朱塞佩·阿尔钦博托 Giuseppe Arcimboldo · 意大利／伦巴第",
      "date": "1563年",
      "material": "椴木板绘画",
      "place": "Kunsthistorisches Museum 绘画馆8厅 · 确认在展",
      "tag": "强烈推荐",
      "significance": "重要藏品",
      "availabilityTag": "",
      "time": "5—8分钟",
      "image": "https://www.khm.at/pics/71/GG_1589_CD_web1.jpg",
      "imageSource": "https://www.khm.at/en/artworks/summer-71",
      "imageCaption": "夏，朱塞佩·阿尔钦博托 Giuseppe Arcimboldo · 意大利／伦巴第，1563年。",
      "imageKind": "work",
      "source": "https://www.khm.at/en/artworks/summer-71",
      "cardSummary": "果实、蔬菜与谷穗既能逐件辨认，又合成一张轮廓清楚的人脸。《夏》把季节物产、自然分类和宫廷肖像错觉压进同一幅画，这套新颖方法也成为阿尔钦博托后世声誉的基础。",
      "preciousWhy": "果实、蔬菜与谷穗既能逐件辨认，又合成一张轮廓清楚的人脸。《夏》把季节物产、自然分类和宫廷肖像错觉压进同一幅画，这套新颖方法也成为阿尔钦博托后世声誉的基础。"
    },
    {
      "id": "vienna-pg-08-madonna-of-the-meadow",
      "ch": "vienna-ch-06-painting",
      "zh": "草地圣母",
      "en": "The Madonna of the Meadow",
      "by": "拉斐尔 Raphael · 意大利",
      "date": "1505 或 1506年",
      "material": "白杨木板",
      "place": "绘画馆 Room I · 确认在展",
      "tag": "强烈推荐",
      "significance": "重要藏品",
      "availabilityTag": "",
      "time": "6—8 分钟",
      "image": "https://www.khm.at/pics/1502/GG_175_Gesamt_CD_web1.jpg",
      "imageSource": "https://www.khm.at/en/artworks/the-madonna-of-the-meadow-1502",
      "imageCaption": "草地圣母，拉斐尔 Raphael · 意大利，1505 或 1506年。",
      "imageKind": "work",
      "source": "https://www.khm.at/en/artworks/the-madonna-of-the-meadow-1502",
      "cardSummary": "拉斐尔把圣母与两个孩子组织成清楚稳定的三角形，让草地上的亲密动作与十字细杖所提示的受难同时进入画面；这是他在佛罗伦萨吸收新构图方法后形成个人语言的关键实例。",
      "preciousWhy": "拉斐尔把圣母与两个孩子组织成清楚稳定的三角形，让草地上的亲密动作与十字细杖所提示的受难同时进入画面；这是他在佛罗伦萨吸收新构图方法后形成个人语言的关键实例。"
    },
    {
      "id": "vienna-pg-14-madonna-with-the-pear",
      "ch": "vienna-ch-06-painting",
      "zh": "梨子圣母",
      "en": "Madonna with the Pear",
      "by": "阿尔布雷希特·丢勒 Albrecht Dürer · 德意志／纽伦堡",
      "date": "1512",
      "material": "椴木板绘画",
      "place": "Kunsthistorisches Museum 绘画馆 XI 厅",
      "tag": "强烈推荐",
      "significance": "重要藏品",
      "availabilityTag": "",
      "time": "5—8 分钟",
      "image": "https://www.khm.at/pics/616/GG_848_CD_web1.jpg",
      "imageSource": "https://www.khm.at/en/artworks/madonna-with-the-pear-616",
      "imageCaption": "梨子圣母，阿尔布雷希特·丢勒 Albrecht Dürer · 德意志／纽伦堡，1512。",
      "imageKind": "work",
      "source": "https://www.khm.at/en/artworks/madonna-with-the-pear-616",
      "cardSummary": "丢勒把北方晚期哥特式的圣母类型与意大利式柔和塑形放进同一幅小画：母子身体一横一竖，暗背景前的一片梨又把亲近的日常动作连到宗教象征。",
      "preciousWhy": "丢勒把北方晚期哥特式的圣母类型与意大利式柔和塑形放进同一幅小画：母子身体一横一竖，暗背景前的一片梨又把亲近的日常动作连到宗教象征。"
    },
    {
      "id": "vienna-pg-09-madonna-of-the-rosary",
      "ch": "vienna-ch-06-painting",
      "zh": "玫瑰经圣母",
      "en": "Madonna of the Rosary",
      "by": "卡拉瓦乔 Caravaggio · 意大利",
      "date": "约 1603",
      "material": "布面绘画",
      "place": "维也纳艺术史博物馆绘画馆 · 确认在展",
      "tag": "强烈推荐",
      "significance": "重要藏品",
      "availabilityTag": "",
      "time": "6—8 分钟",
      "image": "https://www.khm.at/pics/425/GG_147_201904_CD_web1.jpg",
      "imageSource": "https://www.khm.at/en/objectdb/detail/425/",
      "imageCaption": "玫瑰经圣母，卡拉瓦乔 Caravaggio · 意大利，约 1603。",
      "imageKind": "work",
      "source": "https://www.khm.at/en/objectdb/detail/425/",
      "cardSummary": "卡拉瓦乔把玫瑰经念珠画成一件正在人手之间传递的东西：圣母与基督幼儿、圣人、捐赠人和普通信众由此连成一套可见的信仰关系。巨大的祭坛画值得细看，因为它不只描绘一次宗教仪式，还让画外观众看见自己怎样被邀请进入其中。",
      "preciousWhy": "卡拉瓦乔把玫瑰经念珠画成一件正在人手之间传递的东西：圣母与基督幼儿、圣人、捐赠人和普通信众由此连成一套可见的信仰关系。巨大的祭坛画值得细看，因为它不只描绘一次宗教仪式，还让画外观众看见自己怎样被邀请进入其中。"
    },
    {
      "id": "vienna-pg-11-judith-veronese",
      "ch": "vienna-ch-06-painting",
      "zh": "朱迪斯与霍洛芬的头颅",
      "en": "Judith with the Head of Holofernes",
      "by": "保罗·委罗内塞 Paolo Veronese · 意大利（威尼斯）",
      "date": "约 1582 年",
      "material": "布面绘画",
      "place": "维也纳艺术史博物馆·绘画馆 III 厅",
      "tag": "强烈推荐",
      "significance": "重要藏品",
      "availabilityTag": "",
      "time": "4—6 分钟",
      "image": "https://www.khm.at/pics/390/GG_34_HP.jpg",
      "imageSource": "https://www.khm.at/en/artworks/judith-with-the-head-of-holofernes-390",
      "imageCaption": "朱迪斯与霍洛芬的头颅，保罗·委罗内塞 Paolo Veronese · 意大利（威尼斯），约 1582 年。",
      "imageKind": "work",
      "source": "https://www.khm.at/en/artworks/judith-with-the-head-of-holofernes-390",
      "cardSummary": "委罗内塞把斩首后的证据藏进华服与庄严姿态之间：明亮衣裙先抓住视线，暗处的头颅和女仆撑开的袋口随后让整幅画突然变了意思。它值得停留，因为美与恐怖并排出现，却不是同时把答案交出来。",
      "preciousWhy": "委罗内塞把斩首后的证据藏进华服与庄严姿态之间：明亮衣裙先抓住视线，暗处的头颅和女仆撑开的袋口随后让整幅画突然变了意思。它值得停留，因为美与恐怖并排出现，却不是同时把答案交出来。"
    },
    {
      "id": "vienna-pg-10-nymph-and-shepherd",
      "ch": "vienna-ch-06-painting",
      "zh": "宁芙与牧羊人",
      "en": "Nymph and Shepherd",
      "by": "提香 Titian · 意大利威尼斯",
      "date": "约 1570/75",
      "material": "布面绘画",
      "place": "Gemäldegalerie Room II · 确认在展（2026-07-24 核验）",
      "tag": "强烈推荐",
      "significance": "重要藏品",
      "availabilityTag": "",
      "time": "6—8 分钟",
      "image": "https://www.khm.at/pics/1950/GG_1825_CD_web1.jpg",
      "imageSource": "https://www.khm.at/en/artworks/nymph-and-shepherd-1950",
      "imageCaption": "宁芙与牧羊人，提香 Titian · 意大利威尼斯，约 1570/75。",
      "imageKind": "work",
      "source": "https://www.khm.at/en/artworks/nymph-and-shepherd-1950",
      "cardSummary": "一幅无需等人物姓名尘埃落定也能成立的提香晚期画作：女子、持笛男子与剧烈变化的风景，被不同密度的可见笔触连成同一种牧歌气氛。它值得细看之处，正在题材不定与形式高度统一同时发生。",
      "preciousWhy": "一幅无需等人物姓名尘埃落定也能成立的提香晚期画作：女子、持笛男子与剧烈变化的风景，被不同密度的可见笔触连成同一种牧歌气氛。它值得细看之处，正在题材不定与形式高度统一同时发生。"
    }
  ]
}
};
